export type MacroResearchSource = {
  id: string;
  provider: string;
  providerName: string;
  priority: number;
  accessClass: string;
  retrievalMethods: string[];
  categories: string[];
  evidenceValue: string;
  entryUrls: string[];
  testedStatus: string;
  testedAt: string;
  defaultUserAgentRequired: boolean;
  automationPolicy: string;
  limitation: string;
  nextAction: string;
};

const TESTED_AT = "2026-07-08";

export const MACRO_RESEARCH_SOURCES: MacroResearchSource[] = [
  {
    id: "goldman_sachs",
    provider: "goldman_sachs",
    providerName: "Goldman Sachs",
    priority: 1,
    accessClass: "public-summary-licensed-full-report",
    retrievalMethods: ["direct_html", "browser_ua"],
    categories: ["commodities", "macro_outlook", "equity_strategy", "rates_fx", "sector_thematic_research"],
    evidenceValue: "research_narrative",
    entryUrls: [
      "https://www.goldmansachs.com/insights/articles/why-record-high-copper-prices-arent-forecast-to-last",
      "https://www.goldmansachs.com/insights/goldman-sachs-research/macro-outlook-2026-sturdy-growth-stagnant-jobs-stable-prices",
    ],
    testedStatus: "public-html-ok",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: true,
    automationPolicy: "public-summary-only",
    limitation: "Full sell-side research may require licensed access.",
    nextAction: "Use public insight pages as narrative evidence; do not imply access to client-only reports.",
  },
  {
    id: "msci",
    provider: "msci",
    providerName: "MSCI",
    priority: 1,
    accessClass: "public-html-and-pdf",
    retrievalMethods: ["direct_html", "direct_pdf", "browser_ua"],
    categories: ["market_classification", "accessibility_review", "index_review", "methodology_change", "consultation"],
    evidenceValue: "official_index_event",
    entryUrls: [
      "https://www.msci.com/indexes/index-resources/market-classification",
      "https://www.msci.com/downloads/documents/press-releases/media-room/MSCI_2026_MCR_PR.pdf",
    ],
    testedStatus: "public-html-and-pdf-ok",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: true,
    automationPolicy: "official-public-source",
    limitation: "Some document delivery URLs need browser/PDF validation before use.",
    nextAction: "Use classification and review documents as official index/passive-flow event evidence.",
  },
  {
    id: "jpmorgan",
    provider: "jpmorgan",
    providerName: "JPMorgan",
    priority: 1,
    accessClass: "public-summary-licensed-full-report",
    retrievalMethods: ["direct_html", "browser_ua"],
    categories: ["global_outlook", "commodities", "macro_strategy", "credit"],
    evidenceValue: "research_narrative",
    entryUrls: [
      "https://www.jpmorgan.com/insights/global-research/outlook/mid-year-outlook",
      "https://www.jpmorgan.com/insights/global-research/commodities/copper-outlook",
    ],
    testedStatus: "public-html-ok",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: true,
    automationPolicy: "public-summary-only",
    limitation: "Complete institutional research may require licensed access.",
    nextAction: "Use public pages for macro and commodity narrative; do not claim access to private research.",
  },
  {
    id: "ftse_russell_lseg",
    provider: "ftse_russell_lseg",
    providerName: "FTSE Russell / LSEG",
    priority: 1,
    accessClass: "public-html",
    retrievalMethods: ["direct_html", "browser_ua"],
    categories: ["equity_country_classification", "watch_list", "fixed_income_inclusion", "index_methodology"],
    evidenceValue: "official_index_event",
    entryUrls: ["https://www.lseg.com/en/ftse-russell/equity-country-classification"],
    testedStatus: "public-html-ok",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: true,
    automationPolicy: "official-public-source",
    limitation: "Use official pages and documents; keep index event evidence separate from market opinion.",
    nextAction: "Use as benchmark/index classification evidence.",
  },
  {
    id: "blackrock",
    provider: "blackrock",
    providerName: "BlackRock Investment Institute",
    priority: 1,
    accessClass: "public-html",
    retrievalMethods: ["direct_html", "browser_ua"],
    categories: ["asset_allocation", "regime_view", "weekly_commentary", "mega_forces"],
    evidenceValue: "allocation_regime",
    entryUrls: ["https://www.blackrock.com/corporate/insights/blackrock-investment-institute/publications/outlook"],
    testedStatus: "public-html-ok",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: true,
    automationPolicy: "public-source",
    limitation: "Use as allocation/regime context, not as security-level proof.",
    nextAction: "Pair with market data and official macro facts before drawing conclusions.",
  },
  {
    id: "pimco",
    provider: "pimco",
    providerName: "PIMCO",
    priority: 1,
    accessClass: "public-html",
    retrievalMethods: ["direct_html", "browser_ua"],
    categories: ["rates", "bonds", "credit", "duration", "liquidity"],
    evidenceValue: "rates_credit_context",
    entryUrls: ["https://www.pimco.com/us/en/insights/rupture-and-resilience"],
    testedStatus: "public-html-ok",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: true,
    automationPolicy: "public-source",
    limitation: "Use as fixed-income/rates context, not as fund subscription advice.",
    nextAction: "Use for bond-fund and rates-sensitive workflow context.",
  },
  {
    id: "bea",
    provider: "bea",
    providerName: "BEA",
    priority: 1,
    accessClass: "official-api",
    retrievalMethods: ["official_api", "direct_html"],
    categories: ["gdp", "income", "consumption", "trade", "regional_accounts"],
    evidenceValue: "official_macro_fact",
    entryUrls: ["https://apps.bea.gov/api/signup/"],
    testedStatus: "official-api-doc-ok",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: false,
    automationPolicy: "official-api",
    limitation: "API key should be configured for runtime data calls.",
    nextAction: "Use official API for factual macro verification when configured.",
  },
  {
    id: "fred",
    provider: "fred",
    providerName: "FRED",
    priority: 1,
    accessClass: "official-api",
    retrievalMethods: ["official_api", "direct_html"],
    categories: ["rates", "inflation", "employment", "money", "macro_series"],
    evidenceValue: "official_macro_fact",
    entryUrls: ["https://fred.stlouisfed.org/docs/api/fred/"],
    testedStatus: "simple-probe-timeout-needs-retry",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: false,
    automationPolicy: "official-api",
    limitation: "Simple probe timed out in the validation batch; retry through official API path before claiming live data.",
    nextAction: "Use existing FRED-configured macro factor rows when present; retry bounded official API validation when needed.",
  },
  {
    id: "bls",
    provider: "bls",
    providerName: "BLS",
    priority: 1,
    accessClass: "browser-or-official-api",
    retrievalMethods: ["official_api", "browser_ua"],
    categories: ["cpi", "employment", "wages", "labor_market"],
    evidenceValue: "official_macro_fact",
    entryUrls: ["https://www.bls.gov/bls/api_features.htm"],
    testedStatus: "simple-client-blocked",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: true,
    automationPolicy: "official-api-preferred",
    limitation: "Simple HTTP client may be blocked; prefer official API or browser validation.",
    nextAction: "Use official API configuration or browser/WebView verification before source claims.",
  },
  {
    id: "eia",
    provider: "eia",
    providerName: "EIA",
    priority: 1,
    accessClass: "official-api",
    retrievalMethods: ["official_api", "direct_html"],
    categories: ["energy_supply", "energy_demand", "inventory", "oil_gas", "electricity"],
    evidenceValue: "official_commodity_fact",
    entryUrls: ["https://www.eia.gov/opendata/documentation.php"],
    testedStatus: "official-api-doc-ok",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: false,
    automationPolicy: "official-api",
    limitation: "Use official API documentation and configured keys when data calls are needed.",
    nextAction: "Use for commodity supply/demand fact verification.",
  },
  {
    id: "oecd",
    provider: "oecd",
    providerName: "OECD",
    priority: 1,
    accessClass: "browser-public",
    retrievalMethods: ["browser_ua", "webview"],
    categories: ["macro_data_api", "country_risk", "growth", "trade", "policy"],
    evidenceValue: "official_macro_fact",
    entryUrls: ["https://www.oecd.org/en/data/insights/data-explainers/2024/09/api.html"],
    testedStatus: "browser-ua-http-readable",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: true,
    automationPolicy: "browser-compatible-public-page",
    limitation: "Plain HTTP may misclassify access; browser/User-Agent validation succeeded.",
    nextAction: "Use browser/WebView retrieval before classifying OECD pages as blocked.",
  },
  {
    id: "lme",
    provider: "lme",
    providerName: "London Metal Exchange",
    priority: 1,
    accessClass: "browser-public",
    retrievalMethods: ["browser_ua", "webview"],
    categories: ["warehouse_stocks", "inventory", "metals", "pricing_stress"],
    evidenceValue: "official_commodity_fact",
    entryUrls: ["https://www.lme.com/market-data/reports-and-data/warehouse-and-stocks-reports"],
    testedStatus: "playwright-browser-ua-readable",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: true,
    automationPolicy: "browser-compatible-public-page",
    limitation: "Use browser/WebView path when plain HTTP has transport/security issues.",
    nextAction: "Use for metals inventory context after browser retrieval.",
  },
  {
    id: "iea",
    provider: "iea",
    providerName: "IEA",
    priority: 1,
    accessClass: "anti-bot-manual-browser",
    retrievalMethods: ["manual_browser", "webview_user_assisted"],
    categories: ["oil_market_report", "supply", "demand", "inventory", "policy"],
    evidenceValue: "official_commodity_context",
    entryUrls: ["https://www.iea.org/reports/oil-market-report-june-2026"],
    testedStatus: "cloudflare-verification",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: true,
    automationPolicy: "do-not-repeat-automated-fetch-after-challenge",
    limitation: "Public page is valid but reached anti-bot verification in Playwright/curl validation.",
    nextAction: "Use manual/browser-assisted evidence or another official source; report limitation if not completed.",
  },
  {
    id: "opec",
    provider: "opec",
    providerName: "OPEC",
    priority: 1,
    accessClass: "anti-bot-manual-browser",
    retrievalMethods: ["manual_browser", "webview_user_assisted"],
    categories: ["oil_market_report", "supply", "demand", "production", "policy"],
    evidenceValue: "official_commodity_context",
    entryUrls: ["https://www.opec.org/monthly-oil-market-report.html"],
    testedStatus: "cloudflare-verification",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: true,
    automationPolicy: "do-not-repeat-automated-fetch-after-challenge",
    limitation: "Public page is valid but reached anti-bot verification in Playwright/curl validation.",
    nextAction: "Use manual/browser-assisted evidence or another official source; report limitation if not completed.",
  },
  {
    id: "cme",
    provider: "cme",
    providerName: "CME Group",
    priority: 2,
    accessClass: "manual-browser-or-official-data-delivery",
    retrievalMethods: ["manual_browser", "official_data_delivery"],
    categories: ["futures_curve", "commodity_contract_context", "pricing_stress"],
    evidenceValue: "official_market_structure_context",
    entryUrls: ["https://www.cmegroup.com/markets/metals/base/copper.html"],
    testedStatus: "automation-explicitly-blocked",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: true,
    automationPolicy: "do-not-scrape",
    limitation: "Manual browser may open the page, but scripted scraping was explicitly blocked in validation.",
    nextAction: "Use manual evidence or CME official data delivery; do not automate scraping of the page.",
  },
  {
    id: "ubs",
    provider: "ubs",
    providerName: "UBS",
    priority: 2,
    accessClass: "browser-public",
    retrievalMethods: ["browser_ua", "webview"],
    categories: ["year_ahead", "asset_allocation", "macro_outlook", "wealth_management"],
    evidenceValue: "allocation_regime",
    entryUrls: [
      "https://www.ubs.com/us/en/wealth-management/year-ahead.html",
    ],
    testedStatus: "playwright-browser-ua-readable",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: true,
    automationPolicy: "browser-compatible-public-page",
    limitation: "Simple HTTP returned access issues in validation, but Playwright with browser User-Agent loaded readable public content.",
    nextAction: "Use browser/WebView retrieval before classifying UBS public outlook pages as blocked; full client research may still require authorization.",
  },
  {
    id: "sp_dji",
    provider: "sp_dji",
    providerName: "S&P Dow Jones Indices",
    priority: 1,
    accessClass: "security-blocked-or-manual-browser",
    retrievalMethods: ["manual_browser", "official_data_delivery"],
    categories: ["index_review", "index_methodology", "country_classification", "rebalance_event"],
    evidenceValue: "official_index_event",
    entryUrls: ["https://www.spglobal.com/spdji/"],
    testedStatus: "security-blocked-in-automation",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: true,
    automationPolicy: "manual-or-official-delivery-only",
    limitation: "Automation hit security controls during validation; do not retry as a normal runtime fetch.",
    nextAction: "Use manual browser evidence, official documents supplied by the user, or licensed data delivery.",
  },
  {
    id: "fidelity",
    provider: "fidelity",
    providerName: "Fidelity",
    priority: 2,
    accessClass: "security-blocked-or-manual-browser",
    retrievalMethods: ["manual_browser"],
    categories: ["asset_allocation", "market_outlook", "fund_research_context"],
    evidenceValue: "allocation_regime",
    entryUrls: ["https://www.fidelity.com/learning-center/overview"],
    testedStatus: "security-blocked-in-automation",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: true,
    automationPolicy: "manual-browser-only",
    limitation: "Public pages may be browser-readable, but automation validation was blocked.",
    nextAction: "Treat as manual/browser evidence until a legitimate public extraction path is validated.",
  },
  {
    id: "vanguard",
    provider: "vanguard",
    providerName: "Vanguard",
    priority: 2,
    accessClass: "public-html",
    retrievalMethods: ["direct_html", "browser_ua"],
    categories: ["asset_allocation", "capital_market_assumptions", "retirement_investor_context"],
    evidenceValue: "allocation_regime",
    entryUrls: ["https://advisors.vanguard.com/insights/article/2026-economic-and-market-outlook"],
    testedStatus: "public-html-ok",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: true,
    automationPolicy: "public-source-after-validation",
    limitation: "Validated public advisor page; still use as allocation-regime context rather than security-level proof.",
    nextAction: "Use public outlook page as allocation-regime evidence with source URL and retrieved time.",
  },
  {
    id: "state_street",
    provider: "state_street",
    providerName: "State Street Global Advisors",
    priority: 2,
    accessClass: "public-html",
    retrievalMethods: ["direct_html", "browser_ua"],
    categories: ["asset_allocation", "etf_flow_context", "market_outlook"],
    evidenceValue: "allocation_regime",
    entryUrls: ["https://www.ssga.com/us/en/intermediary/insights"],
    testedStatus: "public-html-ok",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: true,
    automationPolicy: "public-source-after-validation",
    limitation: "Validated public insights page; extraction still needs article-level URL selection for strong evidence.",
    nextAction: "Use as allocation/ETF-flow context after selecting a concrete article URL.",
  },
  {
    id: "imf",
    provider: "imf",
    providerName: "IMF",
    priority: 1,
    accessClass: "official-api-and-public-report",
    retrievalMethods: ["official_api", "direct_html", "direct_pdf"],
    categories: ["country_risk", "world_economic_outlook", "external_balance", "fx_liquidity"],
    evidenceValue: "official_macro_fact",
    entryUrls: ["https://www.imf.org/en/Data"],
    testedStatus: "public-html-ok",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: false,
    automationPolicy: "official-public-source",
    limitation: "Official data page validated; use official datasets and public reports rather than research commentary.",
    nextAction: "Catalog IMF datasets/reports before promoting specific series or PDFs.",
  },
  {
    id: "world_bank",
    provider: "world_bank",
    providerName: "World Bank",
    priority: 1,
    accessClass: "official-api",
    retrievalMethods: ["official_api", "direct_html"],
    categories: ["country_macro", "development_indicators", "growth", "external_balance"],
    evidenceValue: "official_macro_fact",
    entryUrls: ["https://datahelpdesk.worldbank.org/knowledgebase/topics/125589-developer-information"],
    testedStatus: "public-html-ok",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: false,
    automationPolicy: "official-api",
    limitation: "Developer information page validated; selected series still require schema/readback registration before workflow use.",
    nextAction: "Add selected World Bank series only after schema/readback is registered.",
  },
  {
    id: "pboc",
    provider: "pboc",
    providerName: "People's Bank of China",
    priority: 1,
    accessClass: "official-public-source",
    retrievalMethods: ["direct_html", "browser_ua", "manual_browser"],
    categories: ["china_liquidity", "monetary_policy", "rates", "open_market_operations", "monetary_statistics"],
    evidenceValue: "official_policy_event",
    entryUrls: ["http://www.pbc.gov.cn/"],
    testedStatus: "public-html-ok",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: true,
    automationPolicy: "official-public-source-after-validation",
    limitation: "Official entry page validated; article/statistical page extraction still needs source-specific date parsing.",
    nextAction: "Validate official public pages and keep policy events separate from numeric macro series.",
  },
  {
    id: "pboc_policy_reports",
    provider: "pboc_policy_reports",
    providerName: "PBOC Monetary Policy Reports",
    priority: 1,
    accessClass: "official-public-source",
    retrievalMethods: ["direct_html", "browser_ua"],
    categories: ["china_liquidity", "monetary_policy", "rates", "policy_report", "official_policy_event"],
    evidenceValue: "official_policy_event",
    entryUrls: ["https://www.pbc.gov.cn/zhengcehuobisi/125207/125227/125957/index.html"],
    testedStatus: "official-subpage-html-ok",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: true,
    automationPolicy: "official-public-source",
    limitation: "List page is retrievable; individual report detail pages should still be extracted and read back before claiming report content.",
    nextAction: "Use as the first direct fallback for China monetary-policy report context when governed content rows are missing.",
  },
  {
    id: "pboc_news_releases",
    provider: "pboc_news_releases",
    providerName: "PBOC News Releases",
    priority: 1,
    accessClass: "official-public-source",
    retrievalMethods: ["direct_html", "browser_ua"],
    categories: ["china_liquidity", "monetary_policy", "open_market_operations", "central_bank_communication", "official_policy_event"],
    evidenceValue: "official_policy_event",
    entryUrls: ["https://www.pbc.gov.cn/goutongjiaoliu/113456/113469/index.html"],
    testedStatus: "official-subpage-html-ok",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: true,
    automationPolicy: "official-public-source",
    limitation: "Communication list is retrievable; operation amounts and rates still require detail-page or numeric-series governance.",
    nextAction: "Use for central-bank communication and liquidity-policy event discovery before manual/browser follow-up.",
  },
  {
    id: "nbs_china",
    provider: "nbs_china",
    providerName: "National Bureau of Statistics of China",
    priority: 1,
    accessClass: "official-public-source",
    retrievalMethods: ["direct_html", "browser_ua", "official_api"],
    categories: ["china_macro_statistics", "cpi_ppi", "industrial_production", "retail_sales", "pmi_context"],
    evidenceValue: "official_macro_fact",
    entryUrls: ["https://www.stats.gov.cn/"],
    testedStatus: "public-html-ok",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: true,
    automationPolicy: "official-public-source-after-validation",
    limitation: "Official entry page validated; official tables/API behavior still needs field-level governance before reusable numeric facts.",
    nextAction: "Separate official NBS numeric series from policy/news narrative.",
  },
  {
    id: "nbs_data_releases",
    provider: "nbs_data_releases",
    providerName: "NBS China Data Releases",
    priority: 1,
    accessClass: "official-public-source",
    retrievalMethods: ["direct_html", "list_to_detail_html", "browser_ua", "official_api"],
    categories: ["china_macro_statistics", "cpi_ppi", "industrial_production", "retail_sales", "data_release"],
    evidenceValue: "official_macro_fact",
    entryUrls: ["https://www.stats.gov.cn/sj/zxfb/"],
    testedStatus: "official-list-detail-html-ok",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: true,
    automationPolicy: "official-public-source-after-validation",
    limitation: "Release list HTML is retrievable and exposes dated official detail links; numeric values from release articles are source evidence, not reusable official series, until a table/API normalizer is registered.",
    nextAction: "Use bounded list-to-detail extraction for China growth, price, activity, PMI, and consumption releases; promote repeated numeric tables only after schema/readback governance.",
  },
  {
    id: "csrc",
    provider: "csrc",
    providerName: "China Securities Regulatory Commission",
    priority: 1,
    accessClass: "official-public-source",
    retrievalMethods: ["direct_html", "browser_ua"],
    categories: ["china_regulation", "capital_market_policy", "listed_company_policy", "fund_policy"],
    evidenceValue: "official_policy_event",
    entryUrls: ["http://www.csrc.gov.cn/"],
    testedStatus: "public-html-ok",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: true,
    automationPolicy: "official-public-source-after-validation",
    limitation: "Official entry page validated; policy events must cite official notices and dates and not infer market direction directly.",
    nextAction: "Validate official notice pages and classify policy events.",
  },
  {
    id: "csrc_policy_notices",
    provider: "csrc_policy_notices",
    providerName: "CSRC Policy Notices",
    priority: 1,
    accessClass: "official-public-source",
    retrievalMethods: ["direct_html", "browser_ua"],
    categories: ["china_regulation", "capital_market_policy", "listed_company_policy", "fund_policy", "official_policy_event"],
    evidenceValue: "official_policy_event",
    entryUrls: ["http://www.csrc.gov.cn/csrc/c100028/common_list.shtml"],
    testedStatus: "official-subpage-html-ok",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: true,
    automationPolicy: "official-public-source",
    limitation: "Notice list is retrievable; individual notice text and effective dates must be extracted before policy conclusions.",
    nextAction: "Use for China securities, fund, listed-company, and market-rule policy event discovery.",
  },
  {
    id: "safe_china",
    provider: "safe_china",
    providerName: "State Administration of Foreign Exchange",
    priority: 1,
    accessClass: "official-public-source",
    retrievalMethods: ["direct_html", "browser_ua"],
    categories: ["china_fx", "capital_flow", "external_balance", "cross_border_finance"],
    evidenceValue: "official_macro_fact",
    entryUrls: ["https://www.safe.gov.cn/"],
    testedStatus: "public-html-ok",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: true,
    automationPolicy: "official-public-source-after-validation",
    limitation: "Official entry page validated; statistics and policy notices need source-specific extraction before workflow use.",
    nextAction: "Use for FX/capital-flow context after source-specific validation.",
  },
  {
    id: "safe_statistics",
    provider: "safe_statistics",
    providerName: "SAFE Statistics",
    priority: 1,
    accessClass: "official-public-source",
    retrievalMethods: ["direct_html", "browser_ua"],
    categories: ["china_fx", "capital_flow", "external_balance", "cross_border_finance", "data_release"],
    evidenceValue: "official_macro_fact",
    entryUrls: ["https://www.safe.gov.cn/safe/tjsj1/index.html"],
    testedStatus: "official-subpage-html-ok",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: true,
    automationPolicy: "official-public-source-after-validation",
    limitation: "Statistics list is retrievable; balance-of-payments and FX series require table-level governance before numeric reuse.",
    nextAction: "Use as the first direct fallback for RMB, FX, capital-flow, and cross-border finance source discovery.",
  },
  {
    id: "china_exchanges",
    provider: "china_exchanges",
    providerName: "China Exchanges",
    priority: 1,
    accessClass: "official-public-source",
    retrievalMethods: ["direct_html", "browser_ua", "manual_browser"],
    categories: ["sse", "szse", "hkex", "futures_exchanges", "listing_rules", "market_structure_event"],
    evidenceValue: "official_policy_event",
    entryUrls: ["https://www.sse.com.cn/", "https://www.szse.cn/", "https://www.hkex.com.hk/"],
    testedStatus: "public-html-ok",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: true,
    automationPolicy: "official-public-source-after-validation",
    limitation: "SSE, SZSE, and HKEX entry pages validated; each exchange still needs disclosure/search extraction handling.",
    nextAction: "Catalog exchange notices and market-structure events as official event evidence.",
  },
  {
    id: "china_exchange_notices",
    provider: "china_exchange_notices",
    providerName: "China Exchange Notices",
    priority: 1,
    accessClass: "official-public-source",
    retrievalMethods: ["direct_html", "browser_ua", "manual_browser"],
    categories: ["sse", "szse", "hkex", "listing_rules", "market_structure_event", "official_policy_event"],
    evidenceValue: "official_policy_event",
    entryUrls: [
      "https://www.sse.com.cn/disclosure/announcement/general/",
      "https://www.szse.cn/disclosure/notice/general/index.html",
      "https://www.hkex.com.hk/News/News-Release?sc_lang=en",
    ],
    testedStatus: "official-subpage-html-ok",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: true,
    automationPolicy: "official-public-source",
    limitation: "Exchange notice pages are retrievable; each notice should be extracted with exchange, notice date, and affected market segment before workflow use.",
    nextAction: "Use for listing, trading-rule, market-structure, and exchange operation event discovery.",
  },
  {
    id: "hkex_news_releases",
    provider: "hkex_news_releases",
    providerName: "HKEX News Releases",
    priority: 1,
    accessClass: "manual-browser-or-webview",
    retrievalMethods: ["webview", "manual_browser", "browser_ua"],
    categories: ["hkex", "listing_rules", "market_structure_event", "official_policy_event"],
    evidenceValue: "official_policy_event",
    entryUrls: ["https://www.hkex.com.hk/News/News-Release?sc_lang=en"],
    testedStatus: "akamai-503-to-simple-http",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: true,
    automationPolicy: "browser-or-manual-evidence-only",
    limitation: "Simple HTTP with browser User-Agent returned Akamai 503 in the current environment; keep HKEX as browser/WebView or manual evidence until a stable official feed/detail path is validated.",
    nextAction: "Use WebView/manual browser evidence for HKEX market-structure or listing-rule events; do not retry as normal direct HTTP fetch.",
  },
  {
    id: "szse_notice_api",
    provider: "szse_notice_api",
    providerName: "SZSE Notice API",
    priority: 1,
    accessClass: "official-api-and-public-report",
    retrievalMethods: ["official_api", "direct_html", "browser_ua"],
    categories: ["szse", "listing_rules", "market_structure_event", "official_policy_event", "api_payload"],
    evidenceValue: "official_policy_event",
    entryUrls: ["https://www.szse.cn/api/disclosure/notice/detail"],
    testedStatus: "official-api-payload-ok",
    testedAt: TESTED_AT,
    defaultUserAgentRequired: true,
    automationPolicy: "official-public-source",
    limitation: "Use only bounded official notice payloads discovered from SZSE public pages; do not treat arbitrary undocumented parameters as reusable data.",
    nextAction: "When a SZSE notice list renders as a JavaScript shell, use the official notice API payload as macro policy-event evidence after macro_research_extract readback.",
  },
];
