export interface ProviderModuleDescriptor {
  provider: string
  title: string
  category: string
  runtimeAvailability: string[]
  agentPaths: Array<'chat' | 'event'>
  requiredAccess: string[]
  capabilityFamilies: string[]
  schemaDecision: string
  cacheReadbackContract: string
  healthEvidence: string
  routingPolicy: string
  uiSurface: string
  discovery: string
  status: string
}

export const providerModuleDescriptorVersion = 'provider-module-descriptor-v2'

export const providerModuleDescriptors: ProviderModuleDescriptor[] = [
  {
    provider: 'local',
    title: 'Local canonical store and reusable cache',
    category: 'local-cache',
    runtimeAvailability: ['workstation'],
    agentPaths: ['chat', 'event'],
    requiredAccess: ['project-data-dir'],
    capabilityFamilies: ['readback', 'cache-coverage', 'stored-evidence'],
    schemaDecision: 'Reusable rows must already belong to a known canonical schema.',
    cacheReadbackContract: 'Local readback is preferred when freshness and coverage satisfy the interface policy.',
    healthEvidence: 'Cache coverage, row counts, source time, and fetched-at are exposed through query/readback results.',
    routingPolicy: 'Use before live providers when the interface supports cache reuse.',
    uiSurface: 'Data Manager, API Health, provider matrix, and agent provenance output.',
    discovery: 'Use interface/query actions, ProviderRouter, and DataStore interface discovery before spending a live provider call.',
    status: 'supported',
  },
  {
    provider: 'eastmoney',
    title: 'EastMoney direct workstation provider',
    category: 'public-direct-http',
    runtimeAvailability: ['workstation'],
    agentPaths: ['chat', 'event'],
    requiredAccess: ['network'],
    capabilityFamilies: ['quote', 'kline', 'sector', 'money-flow', 'limit-pool', 'dragon-tiger', 'fund'],
    schemaDecision: 'Stable direct responses normalize into quote, kline, sector, flow, fund, and event schemas.',
    cacheReadbackContract: 'Successful reusable fetches must persist and read back through canonical query actions.',
    healthEvidence: 'Runtime API stats, data API contract rows, and provider failure queues classify transport and schema issues.',
    routingPolicy: 'Use as public direct route where interface policy and runtime health allow it.',
    uiSurface: 'Data Manager, API Health, provider matrix, and workflow provenance.',
    discovery: 'Use ProviderRouter and ToolCatalog(providerModules).',
    status: 'supported',
  },
  {
    provider: 'tdx',
    title: 'gotdx workstation provider',
    category: 'desktop-sidecar-backed-provider',
    runtimeAvailability: ['workstation'],
    agentPaths: ['chat', 'event'],
    requiredAccess: ['gotdx-sidecar', 'network'],
    capabilityFamilies: ['quote', 'kline', 'index', 'tick', 'transactions'],
    schemaDecision: 'gotdx stable actions normalize into canonical market tables; unsupported protocol surfaces stay diagnostic.',
    cacheReadbackContract: 'Persist stable quote/kline/intraday schemas and reuse local rows before repeat calls.',
    healthEvidence: 'Sidecar availability, runtime transport failures, and contract probe evidence affect provider routing.',
    routingPolicy: 'Preferred for A-share quote/kline/index paths when sidecar and runtime health are good.',
    uiSurface: 'API Health, Data Manager, provider matrix.',
    discovery: 'Use ProviderRouter before broad market refreshes.',
    status: 'supported',
  },
  {
    provider: 'yahoo',
    title: 'Yahoo Finance workstation provider',
    category: 'desktop-sidecar-backed-provider',
    runtimeAvailability: ['workstation'],
    agentPaths: ['chat', 'event'],
    requiredAccess: ['python-yfinance-sidecar', 'global-web-access'],
    capabilityFamilies: ['global-quote', 'global-kline', 'profile', 'news', 'options', 'actions'],
    schemaDecision: 'Sidecar-backed Yahoo/yfinance responses normalize into quote/kline and typed Yahoo research schemas when registered.',
    cacheReadbackContract: 'Use local typed yfinance readback first; live refresh must honor availability evidence.',
    healthEvidence: 'Sidecar status, Yahoo 401/403 evidence, runtime stats, and data API contract rows gate live retries.',
    routingPolicy: 'Use for non-A-share/global workflows only; do not route China A-share data here.',
    uiSurface: 'Data Manager, API Health, global data panels.',
    discovery: 'Use DataStore provider discovery, ToolCatalog(providerModules), and ProviderRouter.',
    status: 'supported',
  },
  {
    provider: 'wind',
    title: 'Wind AIFinMarket credential provider',
    category: 'credential-api-key-provider',
    runtimeAvailability: ['workstation'],
    agentPaths: ['chat', 'event'],
    requiredAccess: ['WIND_API_KEY', 'quota'],
    capabilityFamilies: ['quote', 'fundamental', 'fund', 'macro', 'document'],
    schemaDecision: 'Known Wind schemas persist to canonical market, fundamental, document, and macro tables; free-form payloads remain output-only.',
    cacheReadbackContract: 'Read cache first; live calls require configured credentials and quota.',
    healthEvidence: 'Wind quota/key errors, runtime API stats, and capability gates block broad retries.',
    routingPolicy: 'Use when workflow needs Wind-only evidence or explicit credential-backed refresh.',
    uiSurface: 'Credential status, provider matrix, API Health.',
    discovery: 'Check ProviderRouter and BudgetGovernor before Wind calls.',
    status: 'credential-gated',
  },
  {
    provider: 'tushare',
    title: 'Tushare credential provider',
    category: 'credential-api-key-provider',
    runtimeAvailability: ['workstation'],
    agentPaths: ['chat', 'event'],
    requiredAccess: ['TUSHARE_TOKEN', 'permission-points'],
    capabilityFamilies: ['stock-basic', 'trade-calendar', 'daily-basic', 'index-constituents'],
    schemaDecision: 'Only registered, permission-compatible Tushare schemas persist; disabled statement/fund routes must stay blocked.',
    cacheReadbackContract: 'Use local query/readback before spending Tushare calls.',
    healthEvidence: 'Contract disabled rows and permission failures must be visible to ProviderRouter.',
    routingPolicy: 'Use only for supported credentialed interfaces or explicit diagnostics.',
    uiSurface: 'Provider matrix, API Health, credential/permission gates.',
    discovery: 'Use ProviderRouter and interface availability.',
    status: 'credential-gated',
  },
  {
    provider: 'sina',
    title: 'Sina public finance provider',
    category: 'public-direct-http',
    runtimeAvailability: ['workstation'],
    agentPaths: ['chat', 'event'],
    requiredAccess: ['network'],
    capabilityFamilies: ['quote', 'market-list', 'fundamental-lite'],
    schemaDecision: 'Verified Sina surfaces can be promoted to reusable interfaces when schema/readback value is clear.',
    cacheReadbackContract: 'Persist only governed reusable surfaces; keep known output-only rows explicit.',
    healthEvidence: 'Probe evidence and runtime stats classify availability.',
    routingPolicy: 'Use as public fallback where capability status is supported.',
    uiSurface: 'Provider matrix and provenance output.',
    discovery: 'Use provider matrix before direct Sina routes.',
    status: 'supported',
  },
  {
    provider: 'tencent',
    title: 'Tencent public finance provider',
    category: 'public-direct-http',
    runtimeAvailability: ['workstation'],
    agentPaths: ['chat', 'event'],
    requiredAccess: ['network'],
    capabilityFamilies: ['quote', 'market-list', 'research-lite'],
    schemaDecision: 'Only tested Tencent surfaces with stable schema may become reusable; unsupported exports stay disabled.',
    cacheReadbackContract: 'Reuse only through governed interface rows.',
    healthEvidence: 'Probe evidence and runtime stats classify availability.',
    routingPolicy: 'Use selectively as a public fallback, not as an unbounded scraper.',
    uiSurface: 'Provider matrix and API health summaries.',
    discovery: 'Use provider matrix and ProviderRouter.',
    status: 'supported',
  },
  {
    provider: 'akshare',
    title: 'AkShare workstation sidecar provider',
    category: 'desktop-sidecar-backed-provider',
    runtimeAvailability: ['workstation'],
    agentPaths: ['chat', 'event'],
    requiredAccess: ['python-sidecar', 'network'],
    capabilityFamilies: ['fund', 'news', 'macro', 'compatibility-routes'],
    schemaDecision: 'Registered sidecar routes may persist known schemas; unknown AkShare payloads stay diagnostic.',
    cacheReadbackContract: 'Prefer canonical readback; live sidecar calls require sidecar health.',
    healthEvidence: 'Sidecar health, HTTP status, runtime stats, and probe evidence classify failures.',
    routingPolicy: 'Use only through governed interface or explicit provider diagnostic paths.',
    uiSurface: 'API Health, Data Manager, sidecar status.',
    discovery: 'Use DataStore interface discovery and ProviderRouter.',
    status: 'supported',
  },
  {
    provider: 'macro-official',
    title: 'Official macro numeric APIs',
    category: 'macro-official-api-provider',
    runtimeAvailability: ['workstation'],
    agentPaths: ['chat', 'event'],
    requiredAccess: ['provider-specific-api-key-or-public-access'],
    capabilityFamilies: ['BEA', 'EIA', 'FRED/BLS', 'numeric-series'],
    schemaDecision: 'Official numeric series should persist as structured macro evidence with source time, fetched-at, and series metadata.',
    cacheReadbackContract: 'Use cached series when fresh enough; refresh only targeted series.',
    healthEvidence: 'Missing keys, stale cache, source errors, and extraction failures must be classified.',
    routingPolicy: 'Use as first-class macro evidence for analysis context and invalidation, not direct buy/sell rules.',
    uiSurface: 'Macro Research, Data Manager, workflow artifacts.',
    discovery: 'Use macro evidence/source-reader help before broad macro collection.',
    status: 'credential-gated',
  },
  {
    provider: 'macro-research',
    title: 'Public macro research and report sources',
    category: 'research-source-provider',
    runtimeAvailability: ['workstation'],
    agentPaths: ['chat', 'event'],
    requiredAccess: ['network', 'browser-or-webview-when-needed'],
    capabilityFamilies: ['institutional-research', 'public-pdf', 'source-reader', 'search-discovery'],
    schemaDecision: 'Report title/date/body/key claims/hash should become provenance-bearing macro evidence; blocked pages stay explicit.',
    cacheReadbackContract: 'Reuse extracted evidence by source hash and freshness.',
    healthEvidence: 'Anti-bot, extraction, stale, and missing-source states are evidence.',
    routingPolicy: 'Use after official numeric APIs or when the workflow asks for research context.',
    uiSurface: 'Macro Research full view and source comparison artifacts.',
    discovery: 'Use SourceReader and search/research help.',
    status: 'output-only',
  },
  {
    provider: 'search',
    title: 'Search and research discovery providers',
    category: 'search-research-provider',
    runtimeAvailability: ['workstation'],
    agentPaths: ['chat', 'event'],
    requiredAccess: ['network', 'configured-search-provider'],
    capabilityFamilies: ['macro-discovery', 'news-discovery', 'source-finding'],
    schemaDecision: 'Search results are discovery evidence until source content is fetched, hashed, and classified.',
    cacheReadbackContract: 'Do not treat search snippets as reusable source content.',
    healthEvidence: 'Search provider errors and missing results are classified.',
    routingPolicy: 'Use for discovery, then fetch authoritative sources.',
    uiSurface: 'Research tools, Macro Research, source artifacts.',
    discovery: 'Use Research/WebFetch/SourceReader help.',
    status: 'supported',
  },
  {
    provider: 'xueqiu',
    title: 'Xueqiu simulated trading provider',
    category: 'cookie-account-provider',
    runtimeAvailability: ['workstation'],
    agentPaths: ['chat'],
    requiredAccess: ['cookie/account', 'explicit-user-approval-for-write'],
    capabilityFamilies: ['portfolio', 'transaction-readback', 'simulated-order'],
    schemaDecision: 'Readback evidence is reusable for trading review; write operations require explicit approval and post-action readback.',
    cacheReadbackContract: 'Portfolio and transaction results should preserve provider time and fetched-at.',
    healthEvidence: 'Cookie/account failures and approval state are workflow evidence.',
    routingPolicy: 'Never execute trade side effects without explicit approval state.',
    uiSurface: 'Trade-preparation and simulated-trading artifacts.',
    discovery: 'Use Runbook and FinanceWorkflowState before trading tools.',
    status: 'credential-gated',
  },
  {
    provider: 'ui-artifact',
    title: 'Dashboard and UI artifact producer',
    category: 'ui-artifact-provider',
    runtimeAvailability: ['workstation'],
    agentPaths: ['chat', 'event'],
    requiredAccess: ['project-data-dir', 'renderer-bridge'],
    capabilityFamilies: ['dashboard', 'report', 'webview', 'artifact-readback'],
    schemaDecision: 'UI artifacts should have structured metadata, provenance links, verification status, and path readback.',
    cacheReadbackContract: 'Artifacts must be inspectable after creation and after restart when promised.',
    healthEvidence: 'UI tool results and WorkflowEvidence expose render/open failures.',
    routingPolicy: 'Use only when workflow needs visible artifact output.',
    uiSurface: 'Dashboard panel, WebView, full views, artifact registry.',
    discovery: 'Use UIControl/WebView/ArtifactRegistry help.',
    status: 'supported',
  },
]
