import { create } from 'zustand'
import type { WidgetType } from './useSidebarStore'

export type LanguageMode = 'system' | 'en' | 'zh-CN'
export type ResolvedLanguage = 'en' | 'zh-CN'

const messages = {
  en: {
    appName: 'FinAgent',
    settings: 'Settings',
    workspace: 'Workspace',
    marketPulse: 'Stock Market Pulse',
    watchlist: 'Stock Watchlist',
    fundPulse: 'Fund Pulse',
    fundWatchlist: 'Fund Watchlist',
    apiHealth: 'API Health',
    news: 'News',
    researchWorkspace: 'Research Workspace',
    researchArtifacts: 'artifacts',
    researchCitations: 'citations',
    researchUnverified: 'unverified',
    researchDraft: 'draft',
    researchContinue: 'Continue',
    researchLoading: 'Loading research workspace...',
    researchEmpty: 'No research artifacts yet. Run Research or a report-analysis workflow to collect evidence here.',
    calendar: 'Calendar',
    session: 'Session',
    sessions: 'History',
    portfolio: 'Portfolio',
    data: 'Data',
    quickLaunch: 'Quick Launch',
    market: 'Market',
    marketKpi: 'Market KPI',
    bullish: 'BULLISH',
    bearish: 'BEARISH',
    neutral: 'NEUTRAL',
    limitUp: 'limit up',
    limitDown: 'limit down',
    loadingMarketPulse: 'Loading market pulse...',
    noMarketSnapshot: 'No snapshot available. Will build on next market check.',
    pulseSummaryOnly: 'Summary is available, but no detail rows are cached for this snapshot yet.',
    pulseSummaryOnlyWithFailure: 'Summary is available, but detail rows are unavailable because row-level sources failed or were skipped.',
    partialData: 'Partial data',
    topSectors: 'Top Sectors',
    nonSectorMovers: 'Non-sector Movers',
    hotStocks: 'Hot Stocks',
    pulseIndustry: 'Industry',
    pulseConcept: 'Concept',
    pulseArea: 'Area',
    pulseDerivative: 'Derivative',
    pulseIpo: 'IPO',
    pulseOther: 'Other',
    pulseHeatLabel: 'Heat',
    pulseRankFlat: 'Rank unchanged',
    pulseRankUp: 'Rank up',
    pulseRankDown: 'Rank down',
    pulseActionAnalyze: 'AI analysis',
    pulseActionCompare: 'Compare with',
    pulseActionDashboard: 'Create dashboard',
    pulseActionCopyCode: 'Copy code',
    pulseAddedToWatchlist: 'Added to watchlist',
    pulseAlreadyInWatchlist: 'Already in watchlist',
    tenThousandUnit: '10k',
    hundredMillionUnit: '100M',
    noWidgets: 'No widgets. Use ⌘K to add.',
    openSettings: 'Open Settings',
    commandWidgetCategory: 'Widget',
    commandAppCategory: 'App',
    widgetSidebarSuffix: '(Sidebar)',
    bottomPanelSuffix: '(Bottom Panel)',
    language: 'Language',
    languageSystem: 'System default',
    languageEnglish: 'English',
    languageChinese: 'Chinese (Simplified)',
    close: 'Close',
    open: 'Open',
    active: 'Active',
    collapse: 'Collapse',
    expand: 'Expand',
    keysVisible: '◉ Keys visible',
    keysHidden: '○ Keys hidden',
    saveApply: 'Save & Apply',
    saved: 'Saved',
    tabLlm: 'LLM',
    tabAgent: 'Agent',
    tabFinance: 'Finance',
    tabCalendar: 'Calendar',
    tabGeneral: 'General',
    sectionSession: 'Session',
    sectionPaths: 'Paths',
    autoSaveSession: 'Auto-save session',
    configPath: 'Config',
    sessionsPath: 'Sessions',
    dashboardsPath: 'Dashboards',
    calendarPath: 'Calendar',
    envOverrideNote: 'Env vars override config on startup.',
    loadingApiStats: 'Loading API stats...',
    bySource: 'By Source',
    byEndpoint: 'By Endpoint',
    requests: 'Requests',
    failingEndpoint: 'failing endpoint',
    failingEndpoints: 'failing endpoints',
    noApiCallsInRange: 'No API calls in the last',
    noRecentApiCallsInRange: 'No recent API calls in the last',
    noRequestsInRange: 'No requests in the last',
    calls: 'calls',
    avgShort: 'Avg',
    failShort: 'Fail',
    lastShort: 'Last',
    status: 'Status',
    endpoint: 'Endpoint',
    tool: 'Tool',
    duration: 'Duration',
    error: 'Error',
    closed: 'closed',
    networkBlocked: 'network/proxy blocked upstream request',
    providerContractMismatch: 'provider contract mismatch',
    requestTimedOut: 'request timed out',
    fetchFailedText: 'fetch failed',
    dataManager: 'Data Manager',
    localMarketDataCache: 'Local market data cache. Use the DataStore tool or Data Manager panel for details.',
    openDataManager: 'Open Data Manager',
    events: 'Events',
    processing: 'Processing',
    stopEventAgent: 'Stop event agent',
    backgroundEventAgent: 'Background event agent',
    queueLabel: 'Queue',
    clearQueue: 'Clear queue',
    droppedLabel: 'Dropped',
    pauseQueue: 'Pause queue',
    resumeQueue: 'Resume queue',
    noEventsYet: 'No events yet',
    eventPanelHelp: 'Cron tasks, monitor alerts, and dashboard events appear here',
    reloadDashboardFile: 'Reload dashboard file',
    refreshCurrentPage: 'Refresh current page',
    tradingCalendarTitle: 'Trading Calendar',
    fetching: 'Fetching...',
    fetchYear: 'Fetch',
    weekdaySun: 'Sun',
    weekdayMon: 'Mon',
    weekdayTue: 'Tue',
    weekdayWed: 'Wed',
    weekdayThu: 'Thu',
    weekdayFri: 'Fri',
    weekdaySat: 'Sat',
    tradingDayLabel: 'Trading',
    nonTradingDayLabel: 'Non-trading',
    overrideLabel: 'Override',
    dataYearSummary: 'Data year',
    tradingDaysLabel: 'trading days',
    lastFetchedLabel: 'Last fetched',
    bottomLogs: 'Logs',
    bottomTerminal: 'Terminal',
    bottomTasks: 'Tasks',
    closePanel: 'Close panel',
    logFiles: 'files',
    truncated: 'truncated',
    logDirectoryNotInitialized: 'Log directory is not initialized yet',
    noLogsYet: 'No logs yet.',
    finAgentTerminal: 'FinAgent Terminal',
    bashOutputsHere: 'Bash tool outputs will appear here.',
    noActiveTasks: 'No active tasks.',
    queued: 'Queued...',
    queuedUserInput: 'Queued user input...',
    turnCancelled: 'Turn cancelled',
    generating: 'Generating...',
    thinkingStatus: 'Thinking...',
    writing: 'Writing',
    running: 'Running',
    preparing: 'Preparing',
    toolCall: 'tool call',
    toolCalls: 'tool calls',
    toolErrorLabel: 'Tool error',
    toolResultLabel: 'Tool result',
    chars: 'chars',
    sessionClearedArchived: 'Session cleared and archived.',
    permissionRequired: 'Permission required',
    allow: 'Allow',
    alwaysAllow: 'Always Allow',
    deny: 'Deny',
    stopCancel: 'Stop (cancel)',
    backgroundShort: 'Background',
    askFinAgent: 'Ask FinAgent...',
    send: 'Send',
    thinkingLabel: 'Thinking',
    backgroundTasksAppearHere: 'Background tasks appear here.',
    sendToEventAgent: 'Send to event agent...',
    systemStatus: 'System Status',
    mcpNoServers: 'MCP: no servers configured',
    pluginsNone: 'Plugins: none loaded',
    hooksNone: 'Hooks: none registered',
    sidecarLabel: 'Sidecar',
    mcpServers: 'MCP Servers',
    pluginsLabel: 'Plugins',
    hooksLabel: 'Hooks',
    backgroundedCurrentTurn: 'Backgrounded current turn',
    backgroundedCurrentEventTurn: 'Backgrounded current event-agent turn',
    sessionResumed: 'Session resumed',
    conversationCompacted: 'Conversation compacted',
    suggestedNextPrompt: 'Suggested next prompt',
    errorPrefix: 'Error',
    strategyWizard: 'Strategy Wizard',
    strategyLibrary: 'Strategy Library',
    commandFinanceCategory: 'Finance',
    commandDashboardCategory: 'Dashboard',
    commandWebViewCategory: 'WebView',
    commandChatCategory: 'Chat',
    commandDevCategory: 'Dev',
    commandLayoutCategory: 'Layout',
    commandThemeCategory: 'Theme',
    commandOpenEastMoney: 'Open EastMoney',
    commandOpenXueqiu: 'Open Xueqiu',
    commandClearChat: 'Clear Chat',
    commandToggleDevtools: 'Toggle DevTools',
    commandNewChatSession: 'New Chat Session',
    commandToggleSidebar: 'Toggle Sidebar',
    commandPaletteShortcut: 'Command Palette',
    themeLight: 'Theme: Light',
    themeDark: 'Theme: Dark',
    themeWarm: 'Theme: Warm Light',
    themeSystem: 'Theme: System',
    layoutPrefix: 'Layout',
    typeCommand: 'Type a command...',
    noCommandsFound: 'No commands found',
    newSession: 'New Session',
    resume: 'Resume',
    pause: 'Pause',
    noPastSessions: 'No past sessions',
    noArchivedSessions: 'No archived sessions',
    noSessionPreview: 'No readable messages in this session preview.',
    searchSessions: 'Search sessions',
    searchHistory: 'Search history',
    sessionPanelHelp: 'Resumable working contexts. Resume switches the active chat session.',
    readOnlyPreview: 'Read-only preview. Selecting a row does not change the active session.',
    previewMessages: 'Preview Messages',
    userMessages: 'User',
    assistantMessages: 'Assistant',
    toolMessages: 'Tools',
    watchlistCount: 'Stock Watchlist',
    watchName: 'Name',
    watchPrice: 'Price',
    watchChangePct: 'Chg%',
    watchVolume: 'Vol',
    code: 'Code',
    watchSearchResults: 'Search Results',
    noResults: 'No results',
    fundCode: 'Fund code',
    fundNav: 'NAV',
    fundDailyReturn: 'Daily',
    fundReturn1y: '1Y',
    fundReturnYtd: 'YTD',
    fundRefreshQueued: 'Fund refresh queued',
    fundSearchHint: 'Fund Search',
    fundSuggested: 'Suggested Funds',
    fundTypeToSearch: 'Type fund code or name to search cached fund list.',
    noFundsAddCode: 'No funds. Add a fund code above or refresh fund list.',
    etfMovers: 'ETF Movers',
    fundLeaders: 'Fund Leaders',
    fundNavMovers: 'NAV Movers',
    fundPulseCacheOnly: 'Cached fund and ETF data',
    fundPulseEmpty: 'No cached fund pulse data. Refresh fund list or run an ETF data task first.',
    fundPulseStale: 'Cached fund pulse rows are stale and are hidden until refresh completes.',
    fundPulseLatestDate: 'Latest cached fund date',
    fundPulseRefreshNow: 'Refresh',
    fundPulseRefreshHelp: 'Manual refresh forces a live provider check. Background auto-refresh checks stale fund data at least once per day.',
    fundPulseCacheStatus: 'Cache Status',
    fundPulseTasks: 'Fund Tasks',
    fundListLabel: 'Fund list',
    fundNavLabel: 'Fund NAV',
    fundPerformanceLabel: 'Fund performance',
    etfListLabel: 'ETF list',
    etfQuoteLabel: 'ETF quotes',
    provenanceSource: 'src',
    provenanceAsOf: 'data time',
    provenanceFetched: 'fetched',
    provenanceUpdated: 'updated',
    provenanceCache: 'cache',
    provenanceFresh: 'fresh',
    dataInterface: 'interface',
    provider: 'provider',
    capability: 'capability',
    schema: 'schema',
    table: 'table',
    runtimeProbeTargets: 'Probe targets',
    existingTask: 'Existing task',
    loading: 'Loading...',
    noStocksAddCode: 'No stocks. Add a code above.',
    marketOpenNow: 'Market OPEN',
    marketClosedAfterHours: 'Market CLOSED (after hours)',
    nonTradingDayStatus: 'Non-trading day',
    marketHoursAshare: 'A-share: 09:30-11:30, 13:00-15:00',
    marketHoursHk: 'HK: 09:30-12:00, 13:00-16:00',
    marketHoursUs: 'US: 21:30-04:00 (Beijing)',
    marketDataLoading: 'Market data loading...',
    marketDataUnavailable: 'Market data unavailable',
    noIndexQuotesReturned: 'No index quotes returned',
    indexQuoteBlocked: 'index quote source blocked by network proxy',
    indexQuoteTimedOut: 'index quote request timed out',
    indexQuoteFailed: 'index quote request failed',
    quoteOpen: 'Open',
    quoteHigh: 'High',
    quoteLow: 'Low',
    quotePrevClose: 'Prev Close',
    volumeShort: 'Vol',
    signalAnalysis: 'Signal Analysis',
    buySignal: 'BUY',
    sellSignal: 'SELL',
    holdSignal: 'HOLD',
    backtestPrefix: 'Backtest',
    annualizedReturn: 'Annualized Return',
    maxDrawdown: 'Max Drawdown',
    sharpeRatio: 'Sharpe Ratio',
    winRate: 'Win Rate',
    profitFactor: 'Profit Factor',
    tradesLabel: 'Trades',
    upcoming: 'Upcoming',
    noPortfolioData: 'No portfolio data',
    totalAssets: 'Total Assets',
    profitLoss: 'P&L',
    cash: 'Cash',
    positions: 'Positions',
    defaultGroupName: 'Default',
    unnamed: '(unnamed)',
    defaultTag: 'default',
    htmlPreview: 'HTML Preview',
    strategyWizardTitle: 'Strategy Wizard',
    strategyLibraryTitle: 'Strategy Library',
    strategyLibrarySummary: 'Saved custom strategies with evidence, rerun status, and agent-mediated watch or monitor actions.',
    strategyLibraryCount: 'Saved strategies',
    strategyArtifactContract: 'Artifact contract',
    strategyArtifactContractHint: 'Code-owned strategy artifact schema shared by agent, UI, and tools',
    strategyArtifactCanonical: 'Canonical store',
    strategyArtifactPerItem: 'Per-strategy artifacts',
    strategyArtifactUnavailable: 'Unavailable',
    strategyLibraryPath: 'Library file',
    strategyItemDir: 'Strategy item folder',
    strategyLibraryEmpty: 'No saved strategies yet',
    strategyLibraryEmptyHint: 'Create and save a governed custom strategy from chat or the library creation flow first.',
    strategyLibraryCreate: 'Create strategy',
    strategyLibraryHideCreator: 'Hide creator',
    strategyAssetClass: 'Asset class',
    strategyType: 'Strategy type',
    strategyTypeAll: 'All',
    strategyTypeStock: 'Stock',
    strategyTypeFund: 'Fund',
    strategyTypePortfolio: 'Portfolio',
    strategyTypeEtf: 'ETF / listed',
    strategyTypeUnknown: 'Unknown',
    strategySymbols: 'Symbols',
    strategyEvidenceAction: 'Evidence',
    strategyEvidenceSummary: 'Result',
    strategyDataSummary: 'Data',
    strategyRiskRewardSummary: 'Risk / reward',
    strategyAssumptionSummary: 'Assumptions',
    strategyUpdatedAt: 'Updated',
    strategyRerun: 'Rerun',
    strategyReadEvidence: 'Read evidence',
    strategyAddWatch: 'Add watch',
    strategyCreateMonitor: 'Create monitor',
    strategyStepInput: 'Input',
    strategyStepConfigure: 'Configure',
    strategyStepRun: 'Run',
    strategyStockCode: 'Stock Code',
    strategyDescriptionLabel: 'Describe your strategy (optional, in Chinese or English)',
    strategyDescriptionPlaceholder: 'e.g., Buy when RSI drops below 30, sell above 70, and price is near the lower Bollinger Band',
    strategyNextConfigure: 'Next: Configure',
    strategySelect: 'Select Strategy',
    strategyPeriodBars: 'Data Period (bars)',
    strategyBack: 'Back',
    strategyRunBacktest: 'Run Backtest',
    strategyAiAnalyze: 'AI Analyze',
    strategyRequestSent: 'Backtest request sent to agent. Check the chat for results.',
    strategyRunAnother: 'Run Another',
    strategyPresetRsiName: 'RSI',
    strategyPresetRsiDesc: 'Buy when oversold, sell when overbought',
    strategyPresetMacdName: 'MACD',
    strategyPresetMacdDesc: 'Use golden cross and death cross signals',
    strategyPresetBollName: 'Bollinger',
    strategyPresetBollDesc: 'Buy near the lower band, sell near the upper band',
    strategyPresetEmaCrossName: 'EMA Cross',
    strategyPresetEmaCrossDesc: 'Short-term average crosses long-term average',
    strategyPresetRsiConservativeName: 'RSI Conservative',
    strategyPresetRsiConservativeDesc: 'Use wider RSI thresholds (25/75)',
    strategyPresetBollTightName: 'Bollinger Tight',
    strategyPresetBollTightDesc: 'Use narrower bands (1.5σ)',
    scopeCsi300: 'CSI 300',
    scopeCsi500: 'CSI 500',
    scopeAllAShares: 'All market',
    scopePresetIndex: 'Preset (index)',
    notApplicableShort: 'N/A',
    nameLabel: 'Name',
    providerLabel: 'Provider',
    baseUrl: 'Base URL',
    endpointLabel: 'Endpoint',
    apiKeyLabel: 'API Key',
    apiKeys: 'API Keys',
    modelLabel: 'Model',
    maxTokensLabel: 'Max Tokens',
    contextWindowLabel: 'Context Window',
    thinkingLabelSetting: 'Thinking',
    off: 'Off',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    capabilities: 'Capabilities',
    vision: 'Vision',
    audio: 'Audio',
    extraHeaders: 'Extra Headers',
    userAgent: 'User-Agent',
    headerName: 'Header name',
    headerValue: 'Header value',
    setAsDefault: 'Set as default',
    remove: 'Remove',
    addModel: 'Add Model',
    agentLoop: 'Agent Loop',
    depthLimitUnlimited: 'Depth Limit (0 = unlimited)',
    toolTimeoutMs: 'Tool Timeout (ms)',
    skipChatToolPermissions: 'Skip chat tool permission prompts',
    systemPromptOverride: 'System Prompt Override',
    customSystemPromptHint: 'Custom system prompt (leave empty for default)',
    systemPromptPlaceholder: 'You are FinAgent, an AI-powered finance assistant...',
    customKeys: 'Custom keys:',
    addAction: 'Add',
    keyNamePlaceholder: 'Key name',
    keyValuePlaceholder: 'Key value',
    tushareProToken: 'Tushare Pro Token',
    windAifinMarketApiKey: 'Wind AIFinMarket API Key',
    braveSearchApiKey: 'Brave Search API Key',
    tavilySearchApiKey: 'Tavily Search API Key',
    fredApiKeyName: 'FRED API Key',
    xueqiuCookieLabel: 'Xueqiu Cookie',
    xueqiuPortfolioIds: 'Xueqiu Portfolios',
    addServersPerLine: 'Add servers, one per line:',
    addServers: 'Add Servers',
    openaiCompatible: 'OpenAI / Compatible',
    anthropic: 'Anthropic',
    mainVisionFastExample: 'e.g. Main, Vision, Fast',
    browserDevTools: 'Browser DevTools',
    thousandPerMonthFree: '1000/month free',
    tdxServers: 'TDX Servers',
    refresh: 'Refresh',
    retry: 'Retry',
    run: 'Run',
    accept: 'Accept',
    dismiss: 'Dismiss',
    fullView: 'Full View',
    dataManagerTitle: 'Data Manager',
    dataManagerSummary: 'Manages reusable market cache, scheduled feeds, queue tasks, and source health.',
    dataSurfaceContract: 'Finance Data Contract',
    surfaceDataClassTitle: 'Data class',
    surfaceDataClassDetail: 'Classify the request before choosing cache, provider, or schema behavior.',
    surfaceCachePolicyTitle: 'Cache policy',
    surfaceCachePolicyDetail: 'Read reusable local rows first when freshness and coverage are sufficient.',
    surfaceProviderPolicyTitle: 'Provider policy',
    surfaceProviderPolicyDetail: 'Provider order and gates are code-owned, source-explicit, and rate-aware.',
    surfaceNormalizerTitle: 'Normalizer',
    surfaceNormalizerDetail: 'Source payloads become reusable only through registered parser/normalizer code.',
    surfacePersistTargetTitle: 'Persist target',
    surfacePersistTargetDetail: 'Known schemas write canonical tables with source time separate from ingest time.',
    surfaceReadbackActionTitle: 'Readback action',
    surfaceReadbackActionDetail: 'Same-runtime query paths must read persisted rows before reuse is claimed.',
    surfaceFailureSinkTitle: 'Failure sink',
    surfaceFailureSinkDetail: 'Provider failures go to API Health/task logs, never reusable data tables.',
    surfaceUiSurfaceTitle: 'UI surface',
    surfaceUiSurfaceDetail: 'Panels show source, freshness, failures, and the next safe action.',
    dataHealth: 'Data Health',
    dataHealthy: 'No active failures',
    interfacesLabel: 'Interfaces',
    interfaceLabel: 'Interface',
    schemaLabel: 'Schema',
    liveStatusLabel: 'Live',
    readyLabel: 'Ready',
    gapsLabel: 'Gaps',
    failuresLabel: 'Failures',
    providersLabel: 'Providers',
    providerHealth: 'Provider Health',
    datasetHealth: 'Dataset Health',
    providerGapQueue: 'Provider Gap Queue',
    credentialActivationQueue: 'Credential/Quota Action Queue',
    credentialValidated: 'Credential Validated',
    activationStateLabel: 'Credential state',
    credentialActionQueueHelp: 'Rows stay here only while action is still needed. A row leaves this list when the required credential is configured and live validation succeeds, or when it is reclassified as provider-blocked, quota-blocked, supported, disabled, or not-supported.',
    recheckCredentialState: 'Recheck credential state',
    runtimeProbeStatus: 'Runtime probe',
    runCredentialProbes: 'Run credential probes',
    runUnstableProbes: 'Run unstable probes',
    runFailureProbes: 'Run failure probes',
    runAllProbes: 'Run all actionable probes',
    probeRunning: 'Probe run in progress',
    probeIdle: 'No active probe run',
    lastProbeRun: 'Last probe run',
    selectedProbes: 'Selected probes',
    runtimeProbePath: 'Probe path',
    recommendedProbeTargets: 'Recommended probe targets',
    blockedProbeTargets: 'Blocked probe targets',
    providerProbePacks: 'Provider probe packs',
    noRecommendedProbeTargets: 'No recommended probes from current health evidence',
    noBlockedProbeTargets: 'No blocked probe targets',
    policyDisabledQueue: 'Policy Disabled Queue',
    failureActionQueue: 'Failure Action Queue',
    gapClassLabel: 'Gap class',
    actionPriority: 'Priority',
    failureClassLabel: 'Failure class',
    matrixRowsLabel: 'Matrix rows',
    presenceReasonLabel: 'Why here',
    cacheDecisionLabel: 'Cache decision',
    exitConditionLabel: 'Exit condition',
    retryPolicyLabel: 'Retry policy',
    evidenceLabel: 'Evidence',
    supportedLabel: 'Supported',
    gatedLabel: 'Gated',
    outputOnlyLabel: 'Output-only',
    unstableLabel: 'Unstable',
    liveProbesLabel: 'Live probes',
    passedLabel: 'Passed',
    blockedLabel: 'Blocked',
    datasetsLabel: 'Datasets',
    evidenceGeneratedAt: 'Evidence generated',
    backlogLabel: 'Backlog',
    sourceTimeLabel: 'Source time',
    notAvailable: 'Not available',
    noSupportedCapability: 'No supported capability',
    doctorTitle: 'Doctor',
    doctorOk: 'OK',
    doctorWarning: 'WARN',
    doctorCritical: 'CRIT',
    doctorDatastore: 'DataStore',
    doctorApiFailures: 'Recent API failures',
    doctorQueue: 'Queue',
    doctorStockIdentity: 'Stock identity cache',
    doctorFundIdentity: 'Fund identity cache',
    doctorQuoteCache: 'Quote cache',
    doctorKlineCache: 'K-line cache',
    doctorFeeds: 'Data feeds',
    doctorProviderRoutes: 'Provider routes',
    doctorSchemaRegistry: 'Schema registry',
    doctorDesktopServices: 'Desktop services',
    doctorRuntimePaths: 'Runtime paths',
    doctorSessionHistory: 'Session/history',
    doctorSessionIndex: 'Session search index',
    doctorSummaryOk: 'All local diagnostics passed.',
    doctorCriticalCount: 'critical',
    doctorWarningCount: 'warning',
    doctorDetailDatastoreReady: 'DataStore is ready.',
    doctorDetailDatastoreNotReady: 'DataStore is not initialized.',
    doctorDetailApiClean: 'No API failures in the last 30 minutes.',
    doctorDetailApiFailures: 'failure(s) in the last 30 minutes',
    doctorDetailRoutesOk: 'Core provider routes have at least one configured fallback.',
    doctorDetailRoutesMissing: 'Missing route',
    doctorDetailSchemaRegistryOk: 'registered schemas',
    doctorDetailProviders: 'providers',
    doctorDetailTables: 'tables',
    doctorDetailStaleActive: 'stale',
    doctorDetailSessionIndexPresent: 'Session search index is present.',
    doctorDetailSessionIndexMissing: 'Session search index is missing.',
    doctorNextDatastore: 'Wait for startup to finish before running data tasks.',
    doctorNextApiFailures: 'Inspect API Health and retry only the failed dataset after one source recovers.',
    doctorNextQueue: 'Open Queue and retry the smallest failed task, not the full feed.',
    doctorNextCache: 'Run the targeted feed only when this reusable data is needed.',
    doctorNextFeeds: 'Run one failed feed after checking the matching provider route.',
    doctorNextProviderRoutes: 'Configure the missing provider key or update provider policy before scheduling tasks.',
    doctorNextSchemaRegistry: 'Add parser, normalizer, canonical write, and readback tests before enabling the provider schema.',
    doctorNextDesktopServices: 'Restart FinAgent Workstation after building or starting the missing local service.',
    doctorNextRuntimePaths: 'Fix project data directory permissions before running agent, data, or automation tasks.',
    doctorNextSessionHistory: 'Open a session once or repair session/history directory permissions before relying on resume/history.',
    doctorNextSessionIndex: 'Rebuild or refresh the session search index from sessions/history when search is needed.',
    current: 'current',
    yes: 'yes',
    no: 'no',
    recentFailures: 'Recent Failures',
    likelyCause: 'Likely cause',
    nextStep: 'Next step',
    actionQueued: 'Action queued',
    feedStatus: 'Feed Status',
    goalAutomation: 'Goal Automation',
    goalAutomationUnavailable: 'Goal automation is not initialized.',
    goalAutomationQueued: 'Goal automation queued',
    escalationNeeded: 'escalation needed',
    automationSuggestions: 'Automation Suggestions',
    noAutomationSuggestions: 'No automation suggestions pending.',
    automationSuggestionAccepted: 'Automation suggestion accepted',
    automationSuggestionDismissed: 'Automation suggestion dismissed',
    nextRun: 'Next run',
    cooldown: 'Cooldown',
    trigger: 'Trigger',
    triggerEvidence: 'Evidence',
    recentDecision: 'Recent decision',
    decisionHistory: 'Decision History',
    noDecisionHistory: 'No decisions recorded yet.',
    checkpoint: 'Checkpoint',
    lastResult: 'Last result',
    currentWorkGap: 'Current gap',
    nextAction: 'Next action',
    taskGoalView: 'Task / Goal View',
    objective: 'Objective',
    dataRequirements: 'Data requirements',
    riskBoundary: 'Risk boundary',
    budget: 'Budget',
    doneCriteria: 'Done criteria',
    verification: 'Verification',
    escalation: 'Escalation',
    evidence: 'Evidence',
    dataCauseTimeout: 'provider/network timeout',
    dataNextTimeout: 'keep cached data, retry later, or check source health/API logs before repeating broad fetches',
    dataCauseAllSources: 'every configured source failed for this dataset',
    dataNextAllSources: 'inspect Sources/API Health, then retry only the failed dataset after one source is healthy',
    dataNextGeneric: 'inspect API Health or run a targeted refresh instead of retrying the full queue',
    feedCauseGeneric: 'feed did not complete successfully',
    feedNextGeneric: 'inspect source health, then run this feed only when a source is healthy',
    historicalFeedError: 'Historical feed error',
    rowsLabel: 'rows',
    dataFeeds: 'Data Feeds',
    reusableData: 'Reusable Data',
    coverageTitle: 'Coverage',
    queueTitle: 'Queue',
    sourcesTitle: 'Sources',
    noReusableDataSummary: 'No reusable data summary available yet.',
    dataset: 'Dataset',
    latest: 'Latest',
    agentAccess: 'Agent Access',
    datastoreInitializing: 'DataStore initializing...',
    noFeedConfigs: 'No feed configs found. DataStore may need to be initialized.',
    starting: 'Starting...',
    taskQueued: 'task queued',
    stopped: 'Stopped',
    disabled: 'Disabled',
    enabled: 'Enabled',
    paused: 'Paused',
    idle: 'Idle',
    runningStatus: 'Running',
    historicalStatus: 'Historical',
    feedSymbols: 'symbols',
    lastRun: 'last run',
    enable: 'Enable',
    disable: 'Disable',
    stop: 'Stop',
    runNow: 'Run Now',
    done: 'Done',
    settingsAction: 'Settings',
    scope: 'Scope',
    watchlistStocks: 'Watchlist stocks',
    customCodes: 'Custom codes',
    history: 'History',
    year1: '1 year',
    year3: '3 years',
    year5: '5 years',
    year10: '10 years',
    frequency: 'Frequency',
    manualOnly: 'Manual only',
    every5Min: 'Every 5 min',
    every30Min: 'Every 30 min',
    hourly: 'Hourly',
    afterMarketClose: 'After market close',
    weekly: 'Weekly',
    monthly: 'Monthly',
    quarterly: 'Quarterly',
    yearly: 'Yearly',
    triggerAt: 'Trigger at',
    beijingTime: 'Beijing time',
    sourcePriorityLabel: 'Sources',
    sourcePriorityPlaceholder: 'tdx, eastmoney, akshare',
    sourcePriorityInvalid: 'Invalid source list',
    feedScopeCodesPlaceholder: '600519,000001,...',
    moreCount: 'more',
    noDataDownloadedYet: 'No data downloaded yet.',
    codeLabel: 'Code',
    earliest: 'Earliest',
    noFetchTasks: 'No fetch tasks.',
    sourcePriorityHint: 'Sources are grouped by role. Runtime sources can be tested; gated providers require API keys and are used only for suitable data tasks.',
    routingTitle: 'Routing',
    fetchRoutingTitle: 'Fetch Routing',
    routingHint: 'Shows the provider fallback order after config gates are applied. Normal reads check reusable storage first; this order is used only when data must be fetched.',
    storagePolicyTitle: 'Storage Policy',
    storagePolicyHint: 'Local reusable storage is checked before provider routing. These policies decide whether cached rows are fresh enough.',
    routingReadPathTitle: 'Read path',
    routingReadPathHint: 'UI and agents should query reusable storage first. If cached rows are current enough, no provider call is needed.',
    routingFetchPathTitle: 'Fetch path',
    routingFetchPathHint: 'Provider routing starts on cache miss, stale coverage, explicit refresh, scheduled task, or user-requested live data.',
    noAvailableRoute: 'No available route',
    routeQuote: 'A-share quotes',
    routeKline: 'A-share daily K-line',
    routeIndexQuote: 'Index quotes',
    routeIndexKline: 'Index K-line',
    routeSector: 'Sectors',
    routeLimitPool: 'Limit up/down pool',
    routeDragonTiger: 'Dragon Tiger',
    routeFund: 'Funds / ETF',
    routeFundamental: 'Fundamentals',
    routeMoneyFlow: 'Money flow',
    routeMacro: 'Macro',
    routeIntradayTick: 'Intraday tick',
    routingReasonRealtime: 'High-frequency market reads prefer local/TDX paths, then HTTP fallbacks if the primary path is unavailable.',
    routingReasonEastmoney: 'Market-structure datasets use local cache first, then direct EastMoney where schemas are stable.',
    routingReasonProfessional: 'Research data uses configured professional sources before slower compatibility fallbacks.',
    routingReasonFund: 'Fund views prefer cached fund/ETF data and use EastMoney/AkShare paths to refresh public fund datasets.',
    routingReasonGeneric: 'The agent and queue follow this order when a fetch requires external data.',
    errorsLabel: 'errors',
    test: 'Test',
    testingShort: '...',
    testNotAvailable: 'N/A',
    failedPrefix: 'Failed',
    sourceAkshareName: 'AkShare (Sina / EastMoney)',
    sourceAkshareDesc: 'A-share coverage: quotes, K-line, flows, sectors, fundamentals, funds',
    sourceYfinanceName: 'yfinance (Yahoo)',
    sourceYfinanceDesc: 'US/HK data: K-line, financials, analysts, news, options',
    sourceTdxName: 'TDX',
    sourceTdxDesc: 'Real-time tick, intraday, ex-rights, financials, boards',
    sourceTradingviewName: 'TradingView',
    sourceTradingviewDesc: 'Global screening',
    sourceLocalName: 'Local Cache',
    sourceLocalDesc: 'Reusable persisted data. Always preferred before external calls.',
    sourceEastmoneyDirectName: 'EastMoney Direct',
    sourceEastmoneyDirectDesc: 'Direct REST datasets: sectors, hot rank, limit pool, northbound, dragon tiger.',
    sourceSinaName: 'Sina',
    sourceSinaDesc: 'A-share identity and quote fallback source.',
    sourceTencentName: 'Tencent',
    sourceTencentDesc: 'Market quote fallback source.',
    sourceWindName: 'Wind AIFinMarket',
    sourceWindDesc: 'Professional gated source: quotes, K-line, fundamentals, funds, macro, docs/news.',
    sourceTushareName: 'Tushare Pro',
    sourceTushareDesc: 'Token-gated research data: fundamentals, money flow, funds, trade calendar.',
    sourceStatusUnknown: 'unknown',
    sourceStatusOnline: 'online',
    sourceStatusDegraded: 'degraded',
    sourceStatusOffline: 'offline',
    agentAccessQuote: 'DataStore(query_quote) and MarketData(quote) cache reuse',
    agentAccessApiCache: 'WindMcp identical-request cache',
    agentAccessApiLog: 'API Health and source reliability',
    agentAccessKline: 'DataStore(query_kline), backtest',
    agentAccessFundamental: 'DataStore(query_fundamental), scoring',
    agentAccessGeneric: 'DataStore query actions',
    factorRadar: 'Factor Radar',
    macroFactorLoading: 'Loading macro factors...',
    macroFactorActive: 'active',
    macroFactorBlocked: 'blocked',
    macroFactorSources: 'Sources',
    macroFactorRows: 'Rows',
    macroFactorSchema: 'Schema',
    macroFactorEmpty: 'No macro factor rows yet. Refresh to load verified source families.',
    macroFactorAffected: 'Affected',
    macroFactorSendToAgent: 'Analyze',
    newsFeed: 'News Feed',
    loadingNewsRequiresSidecar: 'Loading news... (requires sidecar)',
    newsSearch: 'Filter news',
    newsSources: 'Sources',
    latestNews: 'Latest',
    analyzeNews: 'Analyze',
    copyTitle: 'Copy title',
    copyNews: 'Copy',
    openNews: 'Open',
    headlineOnlyNews: 'Headline-only alert from source',
    noNews: 'No news loaded. Check provider/source health.',
    layoutDefault: 'Default',
    layoutDefaultDesc: 'Chat + Workspace',
    layoutAnalysis: 'Analysis',
    layoutAnalysisDesc: 'Narrow chat, wide dashboard',
    layoutMonitor: 'Monitor',
    layoutMonitorDesc: 'Full-screen dashboards',
    layoutReading: 'Reading',
    layoutReadingDesc: 'Full-screen WebView',
    layoutTrading: 'Trading',
    layoutTradingDesc: 'Chat + Watchlist + Chart',
    dashboardManagerTitle: 'Agent Dashboards',
    dashboardTemplatesTitle: 'Templates',
    noDashboardsYet: 'No dashboards yet',
    dashboardCreateHint: 'Ask the agent to create one: "generate a KPI dashboard for 600036"',
    dashboardFooterCommandPalette: 'Command Palette',
    dashboardFooterQuickOpen: 'Quick open',
    dashboardFooterAllCommands: 'All commands',
    dashboardTemplateKpi: 'KPI Cards',
    dashboardTemplateKpiDesc: 'Customizable KPI grid with sparklines',
    dashboardTemplateChart: 'Chart',
    dashboardTemplateChartDesc: 'ECharts-based candlestick, line, and bar charts',
    dashboardTemplateMonitor: 'Monitor',
    dashboardTemplateMonitorDesc: 'Auto-refresh monitoring with alerts',
    dashboardTemplateTable: 'Data Table',
    dashboardTemplateTableDesc: 'Sortable data table display',
    dashboardTemplateReport: 'Report',
    dashboardTemplateReportDesc: 'Analysis report rendering',
    dashboardTemplateWeekly: 'Weekly Report',
    dashboardTemplateWeeklyDesc: 'Weekly summary template',
    dashboardTemplateValuation: 'Valuation',
    dashboardTemplateValuationDesc: 'DCF and comparable valuation',
    dashboardTemplateBacktest: 'Backtest',
    dashboardTemplateBacktestDesc: 'Strategy backtest results',
    dashboardCardsCharts: 'Charts',
    dashboardCardsChartsValue: 'K-Line',
    dashboardCardsChartsSub: 'Interactive ECharts view',
    dashboardCardsMonitors: 'Monitors',
    dashboardCardsMonitorsValue: 'Active',
    dashboardCardsMonitorsSub: 'Threshold alerts',
    dashboardCardsBacktestValue: '6 Strategies',
    dashboardCardsBacktestSub: 'RSI MACD BOLL EMA',
    dashboardCardsReports: 'Reports',
    dashboardCardsReportsValue: 'Analysis',
    dashboardCardsReportsSub: 'Agent-generated',
    dashboardCardsValuationValue: 'DCF',
    dashboardCardsValuationSub: 'Comparable analysis',
    dashboardLabelPrefix: 'Dashboard',
    pageFallback: 'Page',
    toolFallback: 'Tool',
    consoleShortcut: 'Console',
    bridgeRendererUnavailable: 'Bridge renderer API is unavailable',
    tasksBackgroundCount: 'background tasks',
    sessionResumedSummary: 'Session resumed',
    messagesLabel: 'messages',
  },
  'zh-CN': {
    appName: 'FinAgent',
    settings: '设置',
    workspace: '工作区',
    marketPulse: '股票市场脉搏',
    watchlist: '股票自选',
    fundPulse: '基金脉搏',
    fundWatchlist: '基金自选',
    apiHealth: '接口健康',
    news: '新闻',
    researchWorkspace: '研究工作台',
    researchArtifacts: '资料',
    researchCitations: '引用',
    researchUnverified: '待验证',
    researchDraft: '草稿',
    researchContinue: '继续研究',
    researchLoading: '正在加载研究工作台...',
    researchEmpty: '暂无研究资料。运行 Research 或报告分析流程后会在这里沉淀证据。',
    calendar: '日历',
    session: '会话',
    sessions: '历史',
    portfolio: '组合',
    data: '数据',
    quickLaunch: '快捷入口',
    market: '市场',
    marketKpi: '市场指标',
    bullish: '强势',
    bearish: '弱势',
    neutral: '震荡',
    limitUp: '涨停',
    limitDown: '跌停',
    loadingMarketPulse: '正在加载市场脉搏...',
    noMarketSnapshot: '暂无市场快照。下次市场检查后生成。',
    pulseSummaryOnly: '当前只有摘要，没有可展示的明细行缓存。',
    pulseSummaryOnlyWithFailure: '当前只有摘要，明细行因行级数据源失败或被跳过而不可用。',
    partialData: '数据不完整',
    topSectors: '领涨板块',
    nonSectorMovers: '其他异动品种',
    hotStocks: '热门个股',
    pulseIndustry: '行业',
    pulseConcept: '概念',
    pulseArea: '区域',
    pulseDerivative: '衍生品',
    pulseIpo: '新股',
    pulseOther: '其他',
    pulseHeatLabel: '热度',
    pulseRankFlat: '排名持平',
    pulseRankUp: '排名上升',
    pulseRankDown: '排名下降',
    pulseActionAnalyze: 'AI 分析',
    pulseActionCompare: '对比分析',
    pulseActionDashboard: '创建仪表板',
    pulseActionCopyCode: '复制代码',
    pulseAddedToWatchlist: '已加入自选',
    pulseAlreadyInWatchlist: '已在自选中',
    tenThousandUnit: '万',
    hundredMillionUnit: '亿',
    noWidgets: '暂无侧栏组件。使用 ⌘K 添加。',
    openSettings: '打开设置',
    commandWidgetCategory: '组件',
    commandAppCategory: '应用',
    widgetSidebarSuffix: '（侧栏）',
    bottomPanelSuffix: '（底部面板）',
    language: '语言',
    languageSystem: '跟随系统',
    languageEnglish: 'English',
    languageChinese: '简体中文',
    close: '关闭',
    open: '打开',
    active: '当前',
    collapse: '收起',
    expand: '展开',
    keysVisible: '◉ 显示密钥',
    keysHidden: '○ 隐藏密钥',
    saveApply: '保存并应用',
    saved: '已保存',
    tabLlm: 'LLM',
    tabAgent: '代理',
    tabFinance: '金融',
    tabCalendar: '日历',
    tabGeneral: '通用',
    sectionSession: '会话',
    sectionPaths: '路径',
    autoSaveSession: '自动保存会话',
    configPath: '配置',
    sessionsPath: '会话',
    dashboardsPath: '仪表板',
    calendarPath: '交易日历',
    envOverrideNote: '环境变量会在启动时覆盖配置。',
    loadingApiStats: '正在加载接口统计...',
    bySource: '按来源',
    byEndpoint: '按接口',
    requests: '请求明细',
    failingEndpoint: '异常接口',
    failingEndpoints: '异常接口',
    noApiCallsInRange: '该时间范围内没有接口调用',
    noRecentApiCallsInRange: '该时间范围内没有最近接口调用',
    noRequestsInRange: '该时间范围内没有请求记录',
    calls: '次调用',
    avgShort: '均值',
    failShort: '失败',
    lastShort: '最近',
    status: '状态',
    endpoint: '接口',
    tool: '工具',
    duration: '耗时',
    error: '错误',
    closed: 'closed',
    networkBlocked: '网络或代理阻断了上游请求',
    providerContractMismatch: 'Provider 返回内容与请求不匹配',
    requestTimedOut: '请求超时',
    fetchFailedText: '请求失败',
    dataManager: '数据管理',
    localMarketDataCache: '本地市场数据缓存。详细情况请使用 DataStore 工具或数据管理面板查看。',
    openDataManager: '打开数据管理',
    events: '事件',
    processing: '处理中',
    stopEventAgent: '停止 Event Agent',
    backgroundEventAgent: '转入后台执行',
    queueLabel: '队列',
    clearQueue: '清空队列',
    droppedLabel: '已丢弃',
    pauseQueue: '暂停队列',
    resumeQueue: '恢复队列',
    noEventsYet: '暂无事件',
    eventPanelHelp: '定时任务、监控告警和仪表板事件会显示在这里',
    reloadDashboardFile: '重新加载看板文件',
    refreshCurrentPage: '刷新当前页面',
    tradingCalendarTitle: '交易日历',
    fetching: '获取中...',
    fetchYear: '获取',
    weekdaySun: '日',
    weekdayMon: '一',
    weekdayTue: '二',
    weekdayWed: '三',
    weekdayThu: '四',
    weekdayFri: '五',
    weekdaySat: '六',
    tradingDayLabel: '交易日',
    nonTradingDayLabel: '非交易',
    overrideLabel: '覆盖',
    dataYearSummary: '数据年份',
    tradingDaysLabel: '个交易日',
    lastFetchedLabel: '上次获取',
    bottomLogs: '日志',
    bottomTerminal: '终端',
    bottomTasks: '任务',
    closePanel: '关闭面板',
    logFiles: '个文件',
    truncated: '已截断',
    logDirectoryNotInitialized: '日志目录尚未初始化',
    noLogsYet: '暂无日志。',
    finAgentTerminal: 'FinAgent 终端',
    bashOutputsHere: 'Bash 工具输出会显示在这里。',
    noActiveTasks: '暂无活动任务。',
    queued: '已排队...',
    queuedUserInput: '用户输入已排队...',
    turnCancelled: '回合已取消',
    generating: '生成中...',
    thinkingStatus: '思考中...',
    writing: '输出中',
    running: '运行中',
    preparing: '准备中',
    toolCall: '工具调用',
    toolCalls: '次工具调用',
    toolErrorLabel: '工具错误',
    toolResultLabel: '工具结果',
    chars: '字符',
    sessionClearedArchived: '会话已清空并归档。',
    permissionRequired: '需要权限',
    allow: '允许',
    alwaysAllow: '始终允许',
    deny: '拒绝',
    stopCancel: '停止（取消）',
    backgroundShort: '后台',
    askFinAgent: '向 FinAgent 提问...',
    send: '发送',
    thinkingLabel: '思考',
    backgroundTasksAppearHere: '后台任务会显示在这里。',
    sendToEventAgent: '发送给 Event Agent...',
    systemStatus: '系统状态',
    mcpNoServers: 'MCP：未配置服务器',
    pluginsNone: '插件：未加载',
    hooksNone: 'Hooks：未注册',
    sidecarLabel: 'Sidecar',
    mcpServers: 'MCP 服务器',
    pluginsLabel: '插件',
    hooksLabel: 'Hooks',
    backgroundedCurrentTurn: '当前回合已转入后台',
    backgroundedCurrentEventTurn: '当前 Event Agent 回合已转入后台',
    sessionResumed: '会话已恢复',
    conversationCompacted: '会话已压缩',
    suggestedNextPrompt: '建议的下一条提示',
    errorPrefix: '错误',
    strategyWizard: '策略向导',
    strategyLibrary: '策略库',
    commandFinanceCategory: '金融',
    commandDashboardCategory: '看板',
    commandWebViewCategory: '网页',
    commandChatCategory: '聊天',
    commandDevCategory: '开发',
    commandLayoutCategory: '布局',
    commandThemeCategory: '主题',
    commandOpenEastMoney: '打开东方财富',
    commandOpenXueqiu: '打开雪球',
    commandClearChat: '清空聊天',
    commandToggleDevtools: '切换开发者工具',
    commandNewChatSession: '新建聊天会话',
    commandToggleSidebar: '切换侧栏',
    commandPaletteShortcut: '命令面板',
    themeLight: '主题：浅色',
    themeDark: '主题：深色',
    themeWarm: '主题：暖色',
    themeSystem: '主题：跟随系统',
    layoutPrefix: '布局',
    typeCommand: '输入命令...',
    noCommandsFound: '没有匹配的命令',
    newSession: '新建会话',
    resume: '恢复',
    pause: '暂停',
    noPastSessions: '暂无历史会话',
    noArchivedSessions: '暂无可恢复会话',
    noSessionPreview: '此历史会话暂无可预览消息。',
    searchSessions: '搜索会话',
    searchHistory: '搜索历史',
    sessionPanelHelp: '可恢复的工作上下文。恢复会切换当前聊天会话。',
    readOnlyPreview: '只读预览。选择一行不会切换当前会话。',
    previewMessages: '预览消息',
    userMessages: '用户',
    assistantMessages: '助手',
    toolMessages: '工具',
    watchlistCount: '股票自选',
    watchName: '名称',
    watchPrice: '价格',
    watchChangePct: '涨跌%',
    watchVolume: '成交量',
    code: '代码',
    watchSearchResults: '搜索结果',
    noResults: '无结果',
    fundCode: '基金代码',
    fundNav: '净值',
    fundDailyReturn: '日涨跌',
    fundReturn1y: '近1年',
    fundReturnYtd: '年初至今',
    fundRefreshQueued: '基金刷新任务已加入队列',
    fundSearchHint: '基金搜索',
    fundSuggested: '推荐基金',
    fundTypeToSearch: '输入基金代码或名称，搜索本地基金列表缓存。',
    noFundsAddCode: '暂无基金，请在上方添加基金代码或刷新基金列表。',
    etfMovers: 'ETF 异动',
    fundLeaders: '基金领先',
    fundNavMovers: '净值异动',
    fundPulseCacheOnly: '使用本地基金和 ETF 缓存',
    fundPulseEmpty: '暂无基金脉搏缓存。请刷新基金列表，或先运行 ETF 数据任务。',
    fundPulseStale: '基金脉搏缓存已过期，当前已隐藏过期行，需刷新后再显示。',
    fundPulseLatestDate: '最新缓存基金日期',
    fundPulseRefreshNow: '刷新',
    fundPulseRefreshHelp: '手动刷新会强制实时检查 provider。后台会至少每天检查一次基金数据是否过期并触发刷新。',
    fundPulseCacheStatus: '缓存状态',
    fundPulseTasks: '基金任务',
    fundListLabel: '基金列表',
    fundNavLabel: '基金净值',
    fundPerformanceLabel: '基金业绩',
    etfListLabel: 'ETF 列表',
    etfQuoteLabel: 'ETF 行情',
    provenanceSource: '来源',
    provenanceAsOf: '数据时点',
    provenanceFetched: '获取',
    provenanceUpdated: '更新',
    provenanceCache: '缓存',
    provenanceFresh: '新取',
    dataInterface: '接口',
    provider: 'Provider',
    capability: '能力',
    schema: 'Schema',
    table: '表',
    runtimeProbeTargets: '探测目标',
    existingTask: '已有任务',
    loading: '加载中...',
    noStocksAddCode: '暂无股票，请先在上方添加代码。',
    marketOpenNow: '交易中',
    marketClosedAfterHours: '已收盘（盘后）',
    nonTradingDayStatus: '非交易日',
    marketHoursAshare: 'A股：09:30-11:30，13:00-15:00',
    marketHoursHk: '港股：09:30-12:00，13:00-16:00',
    marketHoursUs: '美股：21:30-04:00（北京时间）',
    marketDataLoading: '市场数据加载中...',
    marketDataUnavailable: '市场数据暂不可用',
    noIndexQuotesReturned: '未返回指数行情',
    indexQuoteBlocked: '指数行情来源被网络或代理阻断',
    indexQuoteTimedOut: '指数行情请求超时',
    indexQuoteFailed: '指数行情请求失败',
    quoteOpen: '开盘',
    quoteHigh: '最高',
    quoteLow: '最低',
    quotePrevClose: '昨收',
    volumeShort: '成交量',
    signalAnalysis: '信号分析',
    buySignal: '买入',
    sellSignal: '卖出',
    holdSignal: '观望',
    backtestPrefix: '回测',
    annualizedReturn: '年化收益',
    maxDrawdown: '最大回撤',
    sharpeRatio: '夏普比率',
    winRate: '胜率',
    profitFactor: '盈亏比',
    tradesLabel: '交易次数',
    upcoming: '即将发生',
    noPortfolioData: '暂无组合数据',
    totalAssets: '总资产',
    profitLoss: '盈亏',
    cash: '现金',
    positions: '持仓',
    defaultGroupName: '默认',
    unnamed: '（未命名）',
    defaultTag: '默认',
    htmlPreview: 'HTML 预览',
    strategyWizardTitle: '策略向导',
    strategyLibraryTitle: '策略库',
    strategyLibrarySummary: '集中查看已保存自定义策略、证据、可重跑状态，并通过 Agent 进入观察池或监控动作。',
    strategyLibraryCount: '已保存策略',
    strategyArtifactContract: 'Artifact 合同',
    strategyArtifactContractHint: 'Agent、UI 和工具共享的代码侧策略 artifact schema',
    strategyArtifactCanonical: '规范存储',
    strategyArtifactPerItem: '逐策略 artifact',
    strategyArtifactUnavailable: '不可用',
    strategyLibraryPath: '策略库文件',
    strategyItemDir: '策略条目目录',
    strategyLibraryEmpty: '暂无已保存策略',
    strategyLibraryEmptyHint: '先在聊天或策略库创建流程中创建并保存受治理的自定义策略。',
    strategyLibraryCreate: '创建策略',
    strategyLibraryHideCreator: '收起创建',
    strategyAssetClass: '资产类型',
    strategyType: '策略类型',
    strategyTypeAll: '全部',
    strategyTypeStock: '股票',
    strategyTypeFund: '基金',
    strategyTypePortfolio: '组合',
    strategyTypeEtf: 'ETF / 场内',
    strategyTypeUnknown: '未知',
    strategySymbols: '标的',
    strategyEvidenceAction: '证据',
    strategyEvidenceSummary: '结果',
    strategyDataSummary: '数据',
    strategyRiskRewardSummary: '风险收益',
    strategyAssumptionSummary: '假设',
    strategyUpdatedAt: '更新时间',
    strategyRerun: '重跑',
    strategyReadEvidence: '读取证据',
    strategyAddWatch: '加入观察',
    strategyCreateMonitor: '创建监控',
    strategyStepInput: '输入',
    strategyStepConfigure: '配置',
    strategyStepRun: '运行',
    strategyStockCode: '股票代码',
    strategyDescriptionLabel: '描述你的策略（可选，可用中英文）',
    strategyDescriptionPlaceholder: '例如：当RSI低于30时买入，高于70时卖出，同时价格在布林带下轨附近',
    strategyNextConfigure: '下一步：配置',
    strategySelect: '选择策略',
    strategyPeriodBars: '数据周期（bars）',
    strategyBack: '返回',
    strategyRunBacktest: '运行回测',
    strategyAiAnalyze: 'AI 分析',
    strategyRequestSent: '回测请求已发送给 Agent，请到聊天区查看结果。',
    strategyRunAnother: '再次运行',
    strategyPresetRsiName: 'RSI',
    strategyPresetRsiDesc: '超卖时买入，超买时卖出',
    strategyPresetMacdName: 'MACD',
    strategyPresetMacdDesc: '使用金叉与死叉信号',
    strategyPresetBollName: '布林带',
    strategyPresetBollDesc: '靠近下轨买入，靠近上轨卖出',
    strategyPresetEmaCrossName: 'EMA 均线交叉',
    strategyPresetEmaCrossDesc: '短期均线上穿或下穿长期均线',
    strategyPresetRsiConservativeName: 'RSI 保守版',
    strategyPresetRsiConservativeDesc: '使用更宽的 RSI 阈值（25/75）',
    strategyPresetBollTightName: '布林带紧缩版',
    strategyPresetBollTightDesc: '使用更窄的带宽（1.5σ）',
    scopeCsi300: '沪深300',
    scopeCsi500: '中证500',
    scopeAllAShares: '全市场',
    scopePresetIndex: '预设（指数）',
    notApplicableShort: '不适用',
    nameLabel: '名称',
    providerLabel: '提供商',
    baseUrl: '基础地址',
    endpointLabel: '接口',
    apiKeyLabel: 'API 密钥',
    apiKeys: 'API 密钥',
    modelLabel: '模型',
    maxTokensLabel: '最大 Tokens',
    contextWindowLabel: '上下文窗口',
    thinkingLabelSetting: '思考',
    off: '关闭',
    low: '低',
    medium: '中',
    high: '高',
    capabilities: '能力',
    vision: '视觉',
    audio: '音频',
    extraHeaders: '额外请求头',
    userAgent: 'User-Agent',
    headerName: 'Header 名称',
    headerValue: 'Header 值',
    setAsDefault: '设为默认',
    remove: '删除',
    addModel: '添加模型',
    agentLoop: '代理循环',
    depthLimitUnlimited: '深度限制（0 = 不限）',
    toolTimeoutMs: '工具超时（毫秒）',
    skipChatToolPermissions: '跳过聊天工具权限确认',
    systemPromptOverride: '系统提示词覆盖',
    customSystemPromptHint: '自定义系统提示词（留空则使用默认）',
    systemPromptPlaceholder: '你是 FinAgent，一个 AI 驱动的金融助手……',
    customKeys: '自定义键：',
    addAction: '添加',
    keyNamePlaceholder: '键名',
    keyValuePlaceholder: '键值',
    tushareProToken: 'Tushare Pro Token',
    windAifinMarketApiKey: 'Wind AIFinMarket API Key',
    braveSearchApiKey: 'Brave Search API Key',
    tavilySearchApiKey: 'Tavily Search API Key',
    fredApiKeyName: 'FRED API Key',
    xueqiuCookieLabel: '雪球 Cookie',
    xueqiuPortfolioIds: '雪球组合',
    addServersPerLine: '按行添加服务器：',
    addServers: '添加服务器',
    openaiCompatible: 'OpenAI / 兼容接口',
    anthropic: 'Anthropic',
    mainVisionFastExample: '例如 Main、Vision、Fast',
    browserDevTools: '浏览器 DevTools',
    thousandPerMonthFree: '每月 1000 次免费',
    tdxServers: 'TDX 服务器',
    refresh: '刷新',
    retry: '重试',
    run: '运行',
    accept: '接受',
    dismiss: '忽略',
    fullView: '完整视图',
    dataManagerTitle: '数据管理',
    dataManagerSummary: '管理可复用市场缓存、定时数据源任务、队列任务和数据源健康。',
    dataSurfaceContract: '金融数据合同',
    surfaceDataClassTitle: '数据类型',
    surfaceDataClassDetail: '先识别请求类型，再决定缓存、provider 和 schema 行为。',
    surfaceCachePolicyTitle: '缓存策略',
    surfaceCachePolicyDetail: '新鲜度和覆盖度足够时，先读本地可复用数据。',
    surfaceProviderPolicyTitle: 'Provider 策略',
    surfaceProviderPolicyDetail: 'Provider 顺序和门禁由代码控制，明确来源并遵守限速。',
    surfaceNormalizerTitle: 'Normalizer',
    surfaceNormalizerDetail: '来源 payload 只有经过已登记 parser/normalizer 才能变成可复用数据。',
    surfacePersistTargetTitle: '持久化目标',
    surfacePersistTargetDetail: '已知 schema 写入 canonical 表，并区分来源时间和写入时间。',
    surfaceReadbackActionTitle: '读回动作',
    surfaceReadbackActionDetail: '声明可复用前，同一运行时 query 路径必须能读回持久化数据。',
    surfaceFailureSinkTitle: '失败归集',
    surfaceFailureSinkDetail: 'Provider 失败进入 API Health 和任务日志，不写入可复用数据表。',
    surfaceUiSurfaceTitle: 'UI 表面',
    surfaceUiSurfaceDetail: '面板展示来源、freshness、失败原因和下一步安全动作。',
    dataHealth: '数据健康',
    dataHealthy: '暂无活动失败',
    interfacesLabel: '接口',
    interfaceLabel: '接口',
    schemaLabel: 'Schema',
    liveStatusLabel: 'Live',
    readyLabel: '就绪',
    gapsLabel: '缺口',
    failuresLabel: '失败',
    providersLabel: 'Provider',
    providerHealth: 'Provider 健康',
    datasetHealth: '数据集健康',
    providerGapQueue: 'Provider 缺口队列',
    credentialActivationQueue: '凭证/额度待处理队列',
    credentialValidated: '已配置且已验证',
    activationStateLabel: '凭证状态',
    credentialActionQueueHelp: '只有仍然需要处理的行才会留在这里。当所需凭证已配置且实时验证成功，或该能力被重新分类为 provider 拒绝、额度受限、已支持、已禁用或明确不支持时，这一行会移出该列表。',
    recheckCredentialState: '重新检查凭证状态',
    runtimeProbeStatus: '运行时探测',
    runCredentialProbes: '运行凭证探测',
    runUnstableProbes: '运行不稳定探测',
    runFailureProbes: '运行失败探测',
    runAllProbes: '运行全部可操作探测',
    probeRunning: '探测正在运行',
    probeIdle: '当前没有运行中的探测',
    lastProbeRun: '上次探测',
    selectedProbes: '已选探测',
    runtimeProbePath: '探测路径',
    recommendedProbeTargets: '推荐探测目标',
    blockedProbeTargets: '已阻断探测目标',
    providerProbePacks: 'Provider 探测包',
    noRecommendedProbeTargets: '当前健康证据没有推荐探测',
    noBlockedProbeTargets: '没有被阻断的探测目标',
    policyDisabledQueue: '策略禁用队列',
    failureActionQueue: '失败处理队列',
    gapClassLabel: '缺口类型',
    actionPriority: '优先级',
    failureClassLabel: '失败类型',
    matrixRowsLabel: '矩阵行',
    presenceReasonLabel: '保留原因',
    cacheDecisionLabel: '缓存决策',
    exitConditionLabel: '移出条件',
    retryPolicyLabel: '重试策略',
    evidenceLabel: '证据',
    supportedLabel: '已支持',
    gatedLabel: '受限',
    outputOnlyLabel: 'Output-only',
    unstableLabel: '不稳定',
    liveProbesLabel: '真实探测',
    passedLabel: '通过',
    blockedLabel: '阻塞',
    datasetsLabel: '数据集',
    evidenceGeneratedAt: '证据生成时间',
    backlogLabel: '待验证',
    sourceTimeLabel: '来源时间',
    notAvailable: '不可用',
    noSupportedCapability: '暂无已支持能力',
    doctorTitle: '诊断',
    doctorOk: '正常',
    doctorWarning: '警告',
    doctorCritical: '严重',
    doctorDatastore: 'DataStore',
    doctorApiFailures: '近期 API 失败',
    doctorQueue: '队列',
    doctorStockIdentity: '股票身份缓存',
    doctorFundIdentity: '基金身份缓存',
    doctorQuoteCache: '行情缓存',
    doctorKlineCache: 'K 线缓存',
    doctorFeeds: '数据源任务',
    doctorProviderRoutes: 'Provider 路由',
    doctorSchemaRegistry: 'Schema 注册表',
    doctorDesktopServices: '桌面服务',
    doctorRuntimePaths: '运行时路径',
    doctorSessionHistory: '会话/历史',
    doctorSessionIndex: '会话搜索索引',
    doctorSummaryOk: '本地诊断全部通过。',
    doctorCriticalCount: '严重',
    doctorWarningCount: '警告',
    doctorDetailDatastoreReady: 'DataStore 已就绪。',
    doctorDetailDatastoreNotReady: 'DataStore 尚未初始化。',
    doctorDetailApiClean: '最近 30 分钟没有 API 失败。',
    doctorDetailApiFailures: '个最近 30 分钟失败',
    doctorDetailRoutesOk: '核心 provider 路由至少有一个可用 fallback。',
    doctorDetailRoutesMissing: '缺少路由',
    doctorDetailSchemaRegistryOk: '个已注册 schema',
    doctorDetailProviders: '个 provider',
    doctorDetailTables: '张表',
    doctorDetailStaleActive: '个停滞',
    doctorDetailSessionIndexPresent: '会话搜索索引存在。',
    doctorDetailSessionIndexMissing: '会话搜索索引缺失。',
    doctorNextDatastore: '等待启动完成后再运行数据任务。',
    doctorNextApiFailures: '先检查 API Health，至少一个数据源恢复后只重试失败数据集。',
    doctorNextQueue: '打开队列并重试最小的失败任务，不要重跑整个 feed。',
    doctorNextCache: '只有需要这类可复用数据时再运行定向 feed。',
    doctorNextFeeds: '先检查对应 provider 路由，再运行一个失败 feed。',
    doctorNextProviderRoutes: '配置缺失的 provider key，或先更新 provider policy 再调度任务。',
    doctorNextSchemaRegistry: '先补 parser、normalizer、canonical write 和 readback 测试，再启用 provider schema。',
    doctorNextDesktopServices: '构建或启动缺失的本地服务后重启 FinAgent Workstation。',
    doctorNextRuntimePaths: '先修复项目数据目录权限，再运行 agent、数据或自动化任务。',
    doctorNextSessionHistory: '先打开一次会话，或修复 session/history 目录权限，再依赖恢复/历史。',
    doctorNextSessionIndex: '需要搜索时，从 sessions/history 重建或刷新会话搜索索引。',
    current: '当前',
    yes: '是',
    no: '否',
    recentFailures: '近期失败',
    likelyCause: '可能原因',
    nextStep: '下一步',
    actionQueued: '操作已入队',
    feedStatus: '数据源任务状态',
    goalAutomation: '目标自动化',
    goalAutomationUnavailable: '目标自动化尚未初始化。',
    goalAutomationQueued: '目标自动化已入队',
    escalationNeeded: '需要升级处理',
    automationSuggestions: '自动化建议',
    noAutomationSuggestions: '暂无待处理自动化建议。',
    automationSuggestionAccepted: '已接受自动化建议',
    automationSuggestionDismissed: '已忽略自动化建议',
    nextRun: '下次运行',
    cooldown: '冷却',
    trigger: '触发',
    triggerEvidence: '证据',
    recentDecision: '最近决策',
    decisionHistory: '决策历史',
    noDecisionHistory: '暂无决策记录。',
    checkpoint: '检查点',
    lastResult: '上次结果',
    currentWorkGap: '当前缺口',
    nextAction: '下一步',
    taskGoalView: '任务 / 目标视图',
    objective: '目标',
    dataRequirements: '数据需求',
    riskBoundary: '风险边界',
    budget: '预算',
    doneCriteria: '完成标准',
    verification: '验证',
    escalation: '升级条件',
    evidence: '证据',
    dataCauseTimeout: '数据源或网络超时',
    dataNextTimeout: '保留缓存数据，稍后重试，或先检查数据源健康/API 日志，避免重复大范围抓取',
    dataCauseAllSources: '此数据集的所有已配置数据源均失败',
    dataNextAllSources: '先检查数据源/API 健康，再在至少一个数据源恢复后只重试失败数据集',
    dataNextGeneric: '检查 API 健康，或执行定向刷新，避免重试整个队列',
    feedCauseGeneric: '数据源任务未成功完成',
    feedNextGeneric: '先检查数据源健康，再在数据源可用时只运行该任务',
    historicalFeedError: '历史 feed 错误',
    rowsLabel: '行',
    dataFeeds: '数据源任务',
    reusableData: '可复用数据',
    coverageTitle: '覆盖情况',
    queueTitle: '队列',
    sourcesTitle: '数据源',
    noReusableDataSummary: '暂无可复用数据汇总。',
    dataset: '数据集',
    latest: '最新',
    agentAccess: 'Agent 可用方式',
    datastoreInitializing: 'DataStore 初始化中...',
    noFeedConfigs: '未找到 feed 配置，可能还没有初始化 DataStore。',
    starting: '启动中...',
    taskQueued: '任务已入队',
    stopped: '已停止',
    disabled: '已禁用',
    enabled: '已启用',
    paused: '已暂停',
    idle: '空闲',
    runningStatus: '运行中',
    historicalStatus: '历史',
    feedSymbols: '标的',
    lastRun: '上次运行',
    enable: '启用',
    disable: '停用',
    stop: '停止',
    runNow: '立即运行',
    done: '完成',
    settingsAction: '设置',
    scope: '范围',
    watchlistStocks: '自选股',
    customCodes: '自定义代码',
    history: '历史范围',
    year1: '1 年',
    year3: '3 年',
    year5: '5 年',
    year10: '10 年',
    frequency: '频率',
    manualOnly: '仅手动',
    every5Min: '每 5 分钟',
    every30Min: '每 30 分钟',
    hourly: '每小时',
    afterMarketClose: '收盘后',
    weekly: '每周',
    monthly: '每月',
    quarterly: '每季度',
    yearly: '每年',
    triggerAt: '触发时间',
    beijingTime: '北京时间',
    sourcePriorityLabel: '数据源',
    sourcePriorityPlaceholder: 'tdx, eastmoney, akshare',
    sourcePriorityInvalid: '数据源列表无效',
    feedScopeCodesPlaceholder: '600519,000001,...',
    moreCount: '更多',
    noDataDownloadedYet: '尚未下载任何数据。',
    codeLabel: '代码',
    earliest: '最早',
    noFetchTasks: '暂无抓取任务。',
    sourcePriorityHint: '数据源按角色分组。运行时数据源可测试连通性；受限专业数据源需要 API Key，并只在适合的数据任务中使用。',
    routingTitle: '路由',
    fetchRoutingTitle: '抓取路由',
    routingHint: '显示应用配置门控后的真实数据源 fallback 顺序。普通读取先查可复用存储；只有需要抓取数据时才使用这个顺序。',
    storagePolicyTitle: '存储策略',
    storagePolicyHint: '进入 provider routing 前会先检查本地可复用存储。这些策略用于判断缓存是否足够新。',
    routingReadPathTitle: '读取路径',
    routingReadPathHint: 'UI 和 Agent 应先查询可复用存储。缓存数据足够新时，不需要调用外部数据源。',
    routingFetchPathTitle: '抓取路径',
    routingFetchPathHint: '缓存缺失、覆盖过期、显式刷新、定时任务或用户要求实时数据时，才进入 provider routing。',
    noAvailableRoute: '暂无可用路由',
    routeQuote: 'A 股行情',
    routeKline: 'A 股日 K',
    routeIndexQuote: '指数行情',
    routeIndexKline: '指数 K 线',
    routeSector: '板块',
    routeLimitPool: '涨跌停池',
    routeDragonTiger: '龙虎榜',
    routeFund: '基金 / ETF',
    routeFundamental: '基本面',
    routeMoneyFlow: '资金流',
    routeMacro: '宏观',
    routeIntradayTick: '分时 tick',
    routingReasonRealtime: '高频行情读取优先使用本地/TDX 路径，主路径不可用时再进入 HTTP fallback。',
    routingReasonEastmoney: '市场结构类数据先读本地缓存，再使用 schema 稳定的东财直连路径。',
    routingReasonProfessional: '研究类数据优先使用已配置的专业数据源，再进入较慢的兼容 fallback。',
    routingReasonFund: '基金视图优先使用缓存的基金/ETF 数据，并通过东财/AkShare 路径刷新公开基金数据集。',
    routingReasonGeneric: '当抓取需要外部数据时，Agent 和队列按这个顺序选择数据源。',
    errorsLabel: '错误',
    test: '测试',
    testingShort: '...',
    testNotAvailable: '不适用',
    failedPrefix: '失败',
    sourceAkshareName: 'AkShare（新浪 / 东财）',
    sourceAkshareDesc: 'A 股覆盖：行情、K 线、资金流、板块、基本面、基金',
    sourceYfinanceName: 'yfinance（Yahoo）',
    sourceYfinanceDesc: '美股/港股：K 线、财报、分析师、新闻、期权',
    sourceTdxName: 'TDX',
    sourceTdxDesc: '实时 tick、分时、除权、财务、板块',
    sourceTradingviewName: 'TradingView',
    sourceTradingviewDesc: '全球选股扫描',
    sourceLocalName: '本地缓存',
    sourceLocalDesc: '可复用持久化数据。外部调用前优先使用。',
    sourceEastmoneyDirectName: '东财直连',
    sourceEastmoneyDirectDesc: '直连 REST 数据：板块、热门榜、涨跌停、北向、龙虎榜。',
    sourceSinaName: '新浪',
    sourceSinaDesc: 'A 股身份和行情备用数据源。',
    sourceTencentName: '腾讯',
    sourceTencentDesc: '行情备用数据源。',
    sourceWindName: 'Wind AIFinMarket',
    sourceWindDesc: '受限专业数据源：行情、K 线、基本面、基金、宏观、公告/新闻。',
    sourceTushareName: 'Tushare Pro',
    sourceTushareDesc: 'Token 受限研究数据：基本面、资金流、基金、交易日历。',
    sourceStatusUnknown: '未知',
    sourceStatusOnline: '在线',
    sourceStatusDegraded: '降级',
    sourceStatusOffline: '离线',
    agentAccessQuote: 'DataStore(query_quote) 与 MarketData(quote) 缓存复用',
    agentAccessApiCache: 'WindMcp 相同请求缓存',
    agentAccessApiLog: 'API 健康与来源可靠性',
    agentAccessKline: 'DataStore(query_kline)、回测',
    agentAccessFundamental: 'DataStore(query_fundamental)、评分',
    agentAccessGeneric: 'DataStore 查询动作',
    factorRadar: '因子雷达',
    macroFactorLoading: '宏观因子加载中...',
    macroFactorActive: '有效',
    macroFactorBlocked: '受限',
    macroFactorSources: '来源',
    macroFactorRows: '行',
    macroFactorSchema: 'Schema',
    macroFactorEmpty: '暂无宏观因子。点击刷新以加载已验证来源。',
    macroFactorAffected: '影响对象',
    macroFactorSendToAgent: '分析',
    newsFeed: '新闻快讯',
    loadingNewsRequiresSidecar: '新闻加载中...（需要 sidecar）',
    newsSearch: '筛选新闻',
    newsSources: '来源',
    latestNews: '最新',
    analyzeNews: '分析',
    copyTitle: '复制标题',
    copyNews: '复制',
    openNews: '打开',
    headlineOnlyNews: '来源仅提供快讯标题',
    noNews: '暂无新闻。请检查 provider 或数据源健康。',
    layoutDefault: '默认',
    layoutDefaultDesc: '聊天 + 工作区',
    layoutAnalysis: '分析',
    layoutAnalysisDesc: '窄聊天，宽仪表板',
    layoutMonitor: '监控',
    layoutMonitorDesc: '全屏仪表板',
    layoutReading: '阅读',
    layoutReadingDesc: '全屏 WebView',
    layoutTrading: '交易',
    layoutTradingDesc: '聊天 + 自选股 + 图表',
    dashboardManagerTitle: 'Agent 仪表板',
    dashboardTemplatesTitle: '模板',
    noDashboardsYet: '暂无仪表板',
    dashboardCreateHint: '可以让 agent 创建：\"为 600036 生成一个 KPI 仪表板\"',
    dashboardFooterCommandPalette: '命令面板',
    dashboardFooterQuickOpen: '快速打开',
    dashboardFooterAllCommands: '全部命令',
    dashboardTemplateKpi: 'KPI 卡片',
    dashboardTemplateKpiDesc: '可自定义的 KPI 网格与迷你趋势线',
    dashboardTemplateChart: '图表',
    dashboardTemplateChartDesc: '基于 ECharts 的 K 线、折线和柱状图',
    dashboardTemplateMonitor: '监控',
    dashboardTemplateMonitorDesc: '带提醒的自动刷新监控',
    dashboardTemplateTable: '数据表',
    dashboardTemplateTableDesc: '可排序的数据表展示',
    dashboardTemplateReport: '报告',
    dashboardTemplateReportDesc: '分析报告渲染',
    dashboardTemplateWeekly: '周报',
    dashboardTemplateWeeklyDesc: '每周汇总模板',
    dashboardTemplateValuation: '估值',
    dashboardTemplateValuationDesc: 'DCF 与可比估值',
    dashboardTemplateBacktest: '回测',
    dashboardTemplateBacktestDesc: '策略回测结果',
    dashboardCardsCharts: '图表',
    dashboardCardsChartsValue: 'K线',
    dashboardCardsChartsSub: '交互式 ECharts 视图',
    dashboardCardsMonitors: '监控',
    dashboardCardsMonitorsValue: '运行中',
    dashboardCardsMonitorsSub: '阈值提醒',
    dashboardCardsBacktestValue: '6 个策略',
    dashboardCardsBacktestSub: 'RSI MACD BOLL EMA',
    dashboardCardsReports: '报告',
    dashboardCardsReportsValue: '分析',
    dashboardCardsReportsSub: 'Agent 生成',
    dashboardCardsValuationValue: 'DCF',
    dashboardCardsValuationSub: '可比估值分析',
    dashboardLabelPrefix: '仪表板',
    pageFallback: '页面',
    toolFallback: '工具',
    consoleShortcut: '控制台',
    bridgeRendererUnavailable: 'Bridge 渲染层 API 不可用',
    tasksBackgroundCount: '个后台任务',
    sessionResumedSummary: '会话已恢复',
    messagesLabel: '条消息',
  },
} as const

export type TranslationKey = keyof typeof messages.en

interface LanguageState {
  mode: LanguageMode
  resolved: ResolvedLanguage
  setMode: (mode: LanguageMode) => void
  setResolved: (resolved: ResolvedLanguage) => void
}

export const useLanguageStore = create<LanguageState>((set) => ({
  mode: 'system',
  resolved: detectSystemLanguage(),
  setMode: (mode) => set({ mode, resolved: mode === 'system' ? detectSystemLanguage() : resolveMode(mode) }),
  setResolved: (resolved) => set((s) => ({ ...s, resolved })),
}))

export function initLanguage() {
  const store = useLanguageStore.getState()
  store.setResolved(detectSystemLanguage())
  window.agent?.getConfig?.().then((cfg: any) => {
    const mode = normalizeMode(cfg?.language)
    useLanguageStore.getState().setMode(mode)
  }).catch(() => {})
  window.addEventListener('languagechange', () => {
    if (useLanguageStore.getState().mode === 'system') {
      useLanguageStore.getState().setResolved(detectSystemLanguage())
    }
  })
}

export function normalizeMode(value: unknown): LanguageMode {
  return value === 'en' || value === 'zh-CN' || value === 'system' ? value : 'system'
}

function resolveMode(mode: LanguageMode): ResolvedLanguage {
  return mode === 'system' ? detectSystemLanguage() : mode
}

function detectSystemLanguage(): ResolvedLanguage {
  const language = (navigator.language || 'en').toLowerCase()
  return language.startsWith('zh') ? 'zh-CN' : 'en'
}

export function t(key: TranslationKey): string {
  return messages[useLanguageStore.getState().resolved][key]
}

export function useT() {
  const resolved = useLanguageStore((s) => s.resolved)
  return (key: TranslationKey) => messages[resolved][key]
}

export function widgetTitle(type: WidgetType): string {
  switch (type) {
    case 'watchlist': return t('watchlist')
    case 'fund-watchlist': return t('fundWatchlist')
    case 'pulse': return t('marketPulse')
    case 'fund-pulse': return t('fundPulse')
    case 'factor-radar': return t('factorRadar')
    case 'calendar': return t('calendar')
    case 'news': return t('news')
    case 'research': return t('researchWorkspace')
    case 'api-health': return t('apiHealth')
    case 'portfolio': return t('portfolio')
    case 'session': return t('session')
    case 'sessions': return t('sessions')
    case 'data': return t('data')
    case 'strategy-library': return t('strategyLibrary')
  }
}

export function panelTitle(id: 'workspace' | 'settings'): string {
  return id === 'workspace' ? t('workspace') : t('settings')
}

export function dashboardTitle(name: string): string {
  switch (name) {
    case 'kpi':
      return t('marketKpi')
    case 'chart':
      return t('dashboardTemplateChart')
    case 'monitor':
      return t('dashboardTemplateMonitor')
    case 'table':
      return t('dashboardTemplateTable')
    case 'report':
      return t('dashboardTemplateReport')
    case 'report-weekly':
      return t('dashboardTemplateWeekly')
    case 'valuation':
      return t('dashboardTemplateValuation')
    case 'backtest':
      return t('dashboardTemplateBacktest')
    default:
      return name
  }
}

export function bottomTabTitle(type: 'logs' | 'terminal' | 'api-health' | 'tasks'): string {
  switch (type) {
    case 'logs': return t('bottomLogs')
    case 'terminal': return t('bottomTerminal')
    case 'api-health': return t('apiHealth')
    case 'tasks': return t('bottomTasks')
  }
}
