import {
  fetchOnlyFinanceSurfaceContract,
  reusableFinanceSurfaceContract,
} from './finance_surface_contract.mjs'

const reusable = reusableFinanceSurfaceContract
const fetchOnly = fetchOnlyFinanceSurfaceContract

export const matrixDefinitions = [
  {
    id: 'quote_tdx',
    concept: 'quote',
    surfaceContract: reusable({ dataClass: 'stock_quote' }),
    provider: 'TDX/gotdx',
    runtimePath: 'DataStore(action:"tdx") / gotdx / generic ingestion',
    api: 'tdx quote',
    tables: ['quote_snapshot'],
    query: 'query_quote',
    ingestion: ['quote'],
    providerPatterns: ['case \'tdx\'', 'callTdx'],
    testPatterns: ['query_quote', 'quote_snapshot'],
    liveProbe: 'electron_tdx_quote',
    evidence: {
      fetch: ['callTdx'],
      persist: ['saveQuoteSnapshots'],
      readback: ['queryQuote'],
      readbackTest: ['q-ex-quote', 'RBL8 quote snapshots'],
      failureNoPersistTest: ['logs generic TDX failures as API health rows without persisting reusable data'],
      failureSink: ["ds.saveApiCall({ source: 'tdx'"],
    },
    status: 'proven',
  },
  {
    id: 'kline_tdx',
    concept: 'kline',
    surfaceContract: reusable({ dataClass: 'stock_kline' }),
    provider: 'TDX/gotdx',
    runtimePath: 'FetchQueue kline_daily / DataStore(action:"tdx")',
    api: 'tdx kline',
    tables: ['kline_daily'],
    query: 'query_kline',
    ingestion: ['kline', 'index_bars'],
    queueTask: 'kline_daily',
    providerPatterns: ['fetchKlineDaily', 'execKlineDaily'],
    testPatterns: ['query_kline', 'kline_daily'],
    liveProbe: 'electron_tdx_kline',
    evidence: {
      fetch: ['fetchKlineDaily'],
      persist: ['saveKline'],
      readback: ['queryKline'],
      readbackTest: ['q-ex-kline', 'RBL8 daily kline'],
      failureNoPersistTest: ['FetchQueue kline batch accounting', 'saveApiCall'],
      failureSink: ['recordTaskFailure'],
    },
    status: 'proven',
  },
  {
    id: 'stock_list',
    concept: 'stock list',
    surfaceContract: reusable({ dataClass: 'stock_identity', uiSurface: 'required' }),
    provider: 'AkShare/EastMoney/TDX/Tushare',
    runtimePath: 'FetchQueue stock_list / DataStore stock_list',
    api: 'stock list',
    tables: ['stock_list'],
    query: 'stock_list',
    ingestion: ['stock_basic', 'stock_zh_a_spot'],
    queueTask: 'stock_list',
    ipc: 'data:stock-search',
    providerPatterns: ['execStockList', 'fetchStockListA'],
    testPatterns: ['stock_list'],
    liveProbe: 'electron_eastmoney_stock_list',
    evidence: {
      fetch: ['fetchStockListA'],
      uiCacheRead: ['data:stock-search', 'FROM stock_list'],
      persist: ['saveStockList'],
      readback: ['queryStockList'],
      readbackTest: ['q-tdx-list', '000001 平安银行 [SZ]'],
      failureNoPersistTest: ['logs failed direct MarketData TDX action family to API stats without persisting reusable rows', 'stock_list'],
      failureSink: ['recordTaskFailure'],
    },
    status: 'proven',
  },
  {
    id: 'tdx_structured_direct',
    concept: 'TDX structured direct data',
    surfaceContract: reusable({ dataClass: 'tdx_structured_market' }),
    provider: 'TDX/gotdx',
    runtimePath: 'DataStore(action:"tdx") / gotdx structured endpoints',
    api: 'tick/chart/transactions/finance/auction/block/company/XDXR/count/sampling/ExTDX',
    tables: [
      'tick_chart_intraday',
      'transactions',
      'volume_profile',
      'fundamental',
      'stock_company_info',
      'auction_snapshot',
      'unusual_activity',
      'tdx_index_momentum',
      'tdx_top_board',
      'tdx_block_member',
      'xdxr_event',
      'tdx_security_count',
      'tdx_chart_sampling',
      'ex_category',
      'ex_table_entry',
    ],
    query: [
      'query_tick_chart',
      'query_transactions',
      'query_volume_profile',
      'query_fundamental',
      'query_company_info',
      'query_auction',
      'query_unusual',
      'query_momentum',
      'query_top_board',
      'query_tdx_block_member',
      'query_xdxr',
      'query_tdx_count',
      'query_tdx_sampling',
      'query_ex_categories',
      'query_ex_table',
    ],
    ingestion: [
      'tick_chart',
      'history_tick_chart',
      'ex/tick_chart',
      'transactions',
      'history_transactions',
      'history_orders',
      'ex/history_transaction',
      'volume_profile',
      'finance',
      'auction',
      'unusual',
      'index_momentum',
      'top_board',
      'block',
      'ex/board_list',
      'company_info',
      'company_content',
      'company_categories',
      'xdxr',
      'count',
      'ex/count',
      'chart_sampling',
      'ex/chart_sampling',
      'ex/categories',
      'ex/table',
    ],
    providerPatterns: [
      'tdx_tick_chart',
      'tdx_transactions',
      'tdx_finance',
      'tdx_xdxr',
      'tdx_unusual',
      'tdx_count',
      'tdx_sampling',
      'tdx_block',
      'tdx_company_info',
    ],
    testPatterns: [
      'persists gotdx direct TDX and ExQuote actions into canonical tables',
      'query_tdx_block_member',
      'query_ex_categories',
    ],
    liveProbe: 'electron_tdx_tick_chart',
    evidence: {
      fetch: ['tdx_tick_chart', 'tdx_transactions', 'tdx_finance', 'tdx_count'],
      persist: [
        'saveTickChartIntraday',
        'saveTransactions',
        'saveVolumeProfile',
        'saveFundamental',
        'saveStockCompanyInfo',
        'saveAuctionSnapshots',
        'saveUnusualActivity',
        'saveIndexMomentumRows',
        'saveTopBoardRows',
        'saveTdxBlockMembers',
        'saveXdxrEvents',
        'saveTdxSecurityCounts',
        'saveTdxChartSampling',
        'saveExCategories',
        'saveExTableEntries',
      ],
      readback: [
        'queryTickChart',
        'queryTransactions',
        'queryVolumeProfile',
        'queryFundamental',
        'queryCompanyInfo',
        'queryAuction',
        'queryUnusual',
        'queryMomentum',
        'queryTopBoard',
        'queryTdxBlockMember',
        'queryXdxr',
        'queryTdxCount',
        'queryTdxSampling',
        'queryExCategories',
        'queryExTable',
      ],
      readbackTest: ['query_tdx_block_member', 'query_tdx_count', 'query_ex_categories'],
      failureNoPersistTest: ['logs failed direct MarketData TDX action family to API stats without persisting reusable rows'],
      failureSink: ['recordDirectApiFailure'],
    },
    status: 'proven',
  },
  {
    id: 'eastmoney_hot_rank',
    concept: 'hot rank',
    surfaceContract: reusable({ dataClass: 'stock_pulse' }),
    provider: 'EastMoney direct',
    runtimePath: 'MarketData(action:"hot_rank")',
    api: 'stockrank/getAllCurrentList',
    tables: ['hot_rank', 'stock_list'],
    query: 'query_hot_rank',
    ingestion: ['hot_rank', 'stock_hot_rank_em'],
    providerPatterns: ['readHotRank', 'fetchHotRank'],
    testPatterns: ['query_hot_rank', 'hot_rank'],
    liveProbe: 'electron_eastmoney_hot_rank',
    evidence: {
      fetch: ['readHotRank', 'fetchHotRank'],
      persist: ['saveHotRank'],
      readback: ['queryHotRank'],
      readbackTest: ['query_hot_rank', 'Hot rank'],
      failureNoPersistTest: ['logs failed direct MarketData EastMoney advanced actions to API stats without persisting reusable rows', 'hot_rank'],
      failureSink: ['recordDirectApiFailure'],
    },
    status: 'proven',
  },
  {
    id: 'eastmoney_limit_pool',
    concept: 'limit pool',
    surfaceContract: reusable({ dataClass: 'stock_pulse' }),
    provider: 'EastMoney/AkShare',
    runtimePath: 'MarketData limit_up/limit_down and FetchQueue limit_pool',
    api: 'stock_zt_pool_* / push2ex pools',
    tables: ['limit_pool', 'stock_list'],
    query: 'query_limit_pool',
    ingestion: ['stock_zt_pool_em', 'stock_zt_pool_dtgc_em', 'stock_zt_pool_strong_em', 'stock_zt_pool_zbgc_em'],
    queueTask: 'limit_pool',
    providerPatterns: ['fetchLimitUpPool', 'fetchLimitDownPool'],
    testPatterns: ['query_limit_pool', 'limit_pool'],
    liveProbe: 'electron_eastmoney_limit_up',
    evidence: {
      fetch: ['fetchLimitUpPool', 'fetchLimitDownPool'],
      persist: ['saveLimitPool'],
      readback: ['queryLimitPool'],
      readbackTest: ['query_limit_pool', '600519 贵州茅台 up'],
      failureNoPersistTest: ['logs failed MarketData limit-up interface calls to API stats without persisting reusable rows'],
      failureSink: ['recordDirectApiFailure'],
    },
    status: 'proven',
  },
  {
    id: 'eastmoney_sector_dragon_flow',
    concept: 'sector constituents, dragon tiger, and money flow',
    surfaceContract: reusable({ dataClass: 'stock_flow' }),
    provider: 'EastMoney/AkShare',
    runtimePath: 'MarketData sector/dragon_tiger/flow_rank and generic ingestion',
    api: 'industry/concept sectors, LHB, individual fund flow, flow rank',
    tables: ['sector_ranking', 'industry_map', 'dragon_tiger', 'money_flow', 'flow_rank'],
    query: ['query_sector', 'query_industry_map', 'query_dragon_tiger', 'query_money_flow', 'query_flow_rank'],
    ingestion: [
      'stock_board_industry_name_em',
      'stock_board_concept_name_em',
      'sector_ranking',
      'stock_board_industry_cons_em',
      'stock_board_concept_cons_em',
      'sector_cons',
      'stock_lhb_detail_daily_sina',
      'dragon_tiger',
      'stock_individual_fund_flow',
      'stock_individual_fund_flow_rank',
    ],
    providerPatterns: ['readSector', 'readDragonTiger', 'readFlowRank', 'stock_individual_fund_flow'],
    testPatterns: ['sector_ranking', 'query_dragon_tiger', 'query_flow_rank'],
    liveProbe: 'electron_eastmoney_sector_industry',
    evidence: {
      fetch: ['readSector', 'readDragonTiger', 'readFlowRank'],
      persist: ['saveSectorRanking', 'saveIndustryMap', 'saveDragonTiger', 'saveMoneyFlow', 'saveFlowRank'],
      readback: ['querySector', 'queryIndustryMap', 'queryDragonTiger', 'queryMoneyFlow', 'queryFlowRank'],
      readbackTest: ['sector_ranking', 'query_dragon_tiger', 'query_flow_rank'],
      failureNoPersistTest: ['logs failed direct MarketData EastMoney advanced actions to API stats without persisting reusable rows', 'flow_rank'],
      failureSink: ['recordDirectApiFailure'],
    },
    status: 'proven',
  },
  {
    id: 'eastmoney_northbound',
    concept: 'northbound flow and holding',
    surfaceContract: reusable({ dataClass: 'stock_flow' }),
    provider: 'EastMoney direct',
    runtimePath: 'MarketData(action:"northbound") / FetchQueue northbound',
    api: 'RPT_MUTUAL_*',
    tables: ['northbound_flow', 'northbound_holding'],
    query: 'query_northbound',
    ingestion: ['stock_hsgt_hist_em', 'stock_hsgt_hold_stock_em'],
    queueTask: 'northbound',
    providerPatterns: ['readNorthbound', 'fetchNorthbound'],
    testPatterns: ['query_northbound', 'northbound_holding'],
    liveProbe: 'electron_eastmoney_northbound_flow',
    evidence: {
      fetch: ['readNorthbound', 'fetchNorthbound'],
      persist: ['saveNorthboundHolding', 'saveNorthboundFlow'],
      readback: ['queryNorthbound'],
      readbackTest: ['query_northbound', 'Northbound holdings'],
      failureNoPersistTest: ['logs failed direct MarketData EastMoney advanced actions to API stats without persisting reusable rows', 'northbound_flow'],
      failureSink: ['recordDirectApiFailure'],
    },
    status: 'proven',
  },
  {
    id: 'eastmoney_chip',
    concept: 'chip distribution',
    surfaceContract: reusable({ dataClass: 'stock_distribution' }),
    provider: 'EastMoney direct',
    runtimePath: 'MarketData(action:"chip")',
    api: 'RPT_F10_CHIP_DISTRIBUTION',
    tables: ['chip_distribution'],
    query: 'query_chip',
    providerPatterns: ['readChip', 'chip_distribution'],
    testPatterns: ['query_chip', 'chip_distribution'],
    liveProbe: 'electron_eastmoney_chip',
    evidence: {
      fetch: ['readChip'],
      persist: ['saveChipDistribution'],
      readback: ['queryChip'],
      readbackTest: ['query_chip', 'chip distribution'],
      failureNoPersistTest: ['logs failed MarketData chip interface and etf calls to API stats without persisting reusable rows', 'chip'],
      failureSink: ['recordDirectApiFailure'],
    },
    status: 'proven',
  },
  {
    id: 'eastmoney_earnings',
    concept: 'A-share earnings',
    surfaceContract: reusable({ dataClass: 'stock_fundamental' }),
    provider: 'EastMoney direct',
    runtimePath: 'MarketData(action:"earnings")',
    api: 'NewFinanceAnalysis/ZYZBAjaxNew',
    tables: ['fundamental'],
    query: 'query_fundamental',
    providerPatterns: ['readEarnings', 'eastmoney:earnings'],
    testPatterns: ['query_fundamental', 'routes A-share earnings through stock.daily_valuation and persists canonical fundamental rows'],
    liveProbe: 'electron_eastmoney_earnings',
    evidence: {
      fetch: ['readEarnings'],
      persist: ['saveFundamentals'],
      readback: ['queryFundamental'],
      readbackTest: ['routes A-share earnings through stock.daily_valuation and persists canonical fundamental rows', '600519 fundamentals'],
      failureNoPersistTest: ['logs failed MarketData earnings interface calls to API stats without persisting reusable rows'],
      failureSink: ['recordDirectApiFailure'],
    },
    status: 'proven',
  },
  {
    id: 'fund_list',
    concept: 'fund list',
    surfaceContract: reusable({ dataClass: 'fund_identity', uiSurface: 'required' }),
    provider: 'AkShare/EastMoney',
    runtimePath: 'FetchQueue fund_list / FundMarketDataFetchService',
    api: 'fund_open_fund_rank_em',
    tables: ['fund_list'],
    query: 'query_fund_list',
    ingestion: ['fund_open_fund_rank_em'],
    queueTask: 'fund_list',
    ipc: 'data:fund-search',
    providerPatterns: ['readFundList', 'fetchFundList'],
    testPatterns: ['query_fund_list', 'fund_list'],
    liveProbe: 'electron_sidecar_fund_rank',
    evidence: {
      fetch: ['readFundList', 'fetchFundList'],
      uiCacheRead: ['data:fund-search', 'FROM fund_list'],
      persist: ['saveFundList'],
      readback: ['queryFundList'],
      readbackTest: ['query_fund_list', '110011.OF 易方达中小盘'],
      failureNoPersistTest: ['logs generic AkShare failures as API health rows without persisting reusable data'],
      failureSink: ['recordTaskFailure'],
    },
    status: 'proven',
  },
  {
    id: 'fund_nav',
    concept: 'fund NAV',
    surfaceContract: reusable({ dataClass: 'fund_nav', uiSurface: 'required' }),
    provider: 'AkShare/EastMoney',
    runtimePath: 'FetchQueue fund_nav / FundMarketDataFetchService',
    api: 'fund_open_fund_info_em',
    tables: ['fund_nav'],
    query: 'query_fund_nav',
    ingestion: ['fund_open_fund_info_em'],
    queueTask: 'fund_nav',
    ipc: 'data:fund-watchlist',
    providerPatterns: ['readFundNav', 'fetchFundNav'],
    testPatterns: ['query_fund_nav', 'fund_nav'],
    liveProbe: 'electron_sidecar_fund_nav',
    evidence: {
      fetch: ['readFundNav', 'fetchFundNav'],
      uiCacheRead: ['data:fund-watchlist', 'FROM fund_nav', 'FROM fund_list'],
      persist: ['saveFundNav'],
      readback: ['queryFundNav'],
      readbackTest: ['query_fund_nav', '110011 fund NAV'],
      failureNoPersistTest: ['logs generic AkShare failures as API health rows without persisting reusable data'],
      failureSink: ['recordTaskFailure'],
    },
    status: 'proven',
  },
  {
    id: 'fund_holding_manager',
    concept: 'fund holding and manager',
    surfaceContract: reusable({ dataClass: 'fund_research' }),
    provider: 'AkShare',
    runtimePath: 'FetchQueue fund_holding/fund_manager',
    api: 'fund_portfolio_hold_em / fund_manager_em',
    tables: ['fund_holding', 'fund_manager'],
    query: ['query_fund_holding', 'query_fund_manager'],
    ingestion: ['fund_portfolio_hold_em', 'fund_manager_em'],
    queueTask: ['fund_holding', 'fund_manager'],
    providerPatterns: ['fetchFundHolding', 'fetchFundManagers'],
    testPatterns: ['query_fund_holding', 'query_fund_manager'],
    liveProbe: 'electron_sidecar_fund_holding',
    evidence: {
      fetch: ['fetchFundHolding', 'fetchFundManagers'],
      persist: ['saveFundHolding', 'saveFundManagers'],
      readback: ['queryFundHolding', 'queryFundManager'],
      readbackTest: ['query_fund_holding', 'query_fund_manager'],
      failureNoPersistTest: ['logs generic AkShare failures as API health rows without persisting reusable data'],
      failureSink: ['recordTaskFailure'],
    },
    status: 'proven',
  },
  {
    id: 'etf_quotes',
    concept: 'ETF quotes',
    surfaceContract: reusable({ dataClass: 'fund_pulse', uiSurface: 'required' }),
    provider: 'EastMoney direct',
    runtimePath: 'FetchQueue etf_quotes / MarketData(action:"etf")',
    api: 'fund ETF clist',
    tables: ['stock_list', 'quote_snapshot'],
    query: ['stock_list', 'query_quote'],
    queueTask: 'etf_quotes',
    ipc: 'data:fund-pulse',
    providerPatterns: ['readEtfQuotes', 'fetchEtfQuotes'],
    testPatterns: ['query_quote', 'stock_type: \'etf\''],
    liveProbe: 'electron_eastmoney_etf',
    evidence: {
      fetch: ['readEtfQuotes', 'fetchEtfQuotes'],
      uiCacheRead: ['data:fund-pulse', "stock_type = 'etf'", 'quote_snapshot'],
      persist: ['saveEtfQuotes', 'saveQuoteSnapshots'],
      readback: ['queryQuote', 'queryStockList'],
      readbackTest: ['stock_type: \'etf\'', 'query_quote'],
      failureNoPersistTest: ['logs failed MarketData chip interface and etf calls to API stats without persisting reusable rows', 'etf'],
      failureSink: ['recordTaskFailure'],
    },
    status: 'proven',
  },
  {
    id: 'news_sidecar',
    concept: 'finance news',
    surfaceContract: reusable({ dataClass: 'finance_news' }),
    provider: 'AkShare/news sidecar',
    runtimePath: 'sidecar /news',
    api: '/news',
    tables: ['finance_news'],
    query: 'query_finance_news',
    providerPatterns: ['/news', 'finance_news'],
    testPatterns: ['routes sidecar news through the data API requirement boundary', 'query_finance_news'],
    liveProbe: 'electron_sidecar_news',
    evidence: {
      fetch: ['/news', 'finance_news'],
      persist: ['saveFinanceNews'],
      readback: ['queryFinanceNews'],
      readbackTest: ['query_finance_news', 'cached headline'],
      failureNoPersistTest: ['records sidecar news failures in API health with interface provenance'],
      failureSink: ['BridgeIPC', 'source: \'sidecar\'', 'saveApiCall'],
    },
    status: 'proven',
    note: 'Broad finance news now routes through news.finance_feed and persists canonical finance_news rows with cache/readback provenance.',
  },
  {
    id: 'akshare_margin_trading',
    concept: 'margin trading',
    surfaceContract: reusable({ dataClass: 'margin_trading' }),
    provider: 'AkShare sidecar',
    runtimePath: 'DataStore(action:"margin_trading") / sidecar /margin',
    api: '/margin',
    tables: ['margin_trading'],
    query: 'query_margin_trading',
    ingestion: ['margin'],
    providerPatterns: ['marginTrading', '/margin', 'market.margin_trading'],
    testPatterns: ['query_margin_trading', 'margin_trading'],
    liveProbe: 'electron_sidecar_margin',
    evidence: {
      fetch: ['marginTrading', '/margin'],
      persist: ['saveMarginTradingRows'],
      readback: ['queryMarginTrading', 'queryMarginTradingRows'],
      readbackTest: ['query_margin_trading', 'routes query_margin_trading through DataStoreTool readback'],
      failureNoPersistTest: ['AkShare margin trading failed', 'saveApiCall'],
      failureSink: ["source: 'akshare'", "interface_id: 'market.margin_trading'", 'saveApiCall'],
    },
    status: 'proven',
  },
  {
    id: 'yfinance_profile_statements',
    concept: 'Yahoo profile, statements, recommendations, holders, and insiders',
    surfaceContract: reusable({ dataClass: 'global_fundamentals' }),
    provider: 'yfinance sidecar',
    runtimePath: 'MarketData(action:"yahoo_earnings") / DataStore(action:"yfinance")',
    api: 'info, statements, recommendations, holders, insiders',
    tables: [
      'yfinance_profile_fields',
      'yfinance_statement_items',
      'yfinance_recommendations',
      'yfinance_holders',
      'yfinance_insider_transactions',
    ],
    query: 'query_yfinance',
    ingestion: [
      'info',
      'get_info',
      'financials',
      'quarterly_financials',
      'income_stmt',
      'quarterly_income_stmt',
      'balance_sheet',
      'balancesheet',
      'quarterly_balance_sheet',
      'quarterly_balancesheet',
      'cash_flow',
      'cashflow',
      'quarterly_cash_flow',
      'quarterly_cashflow',
      'earnings_dates',
      'earnings_estimate',
      'earnings_history',
      'eps_revisions',
      'eps_trend',
      'recommendations',
      'recommendations_summary',
      'upgrades_downgrades',
      'institutional_holders',
      'mutualfund_holders',
      'major_holders',
      'insider_transactions',
    ],
    providerPatterns: ['fetchEarnings', 'yahoo_earnings', 'queryYfinance'],
    testPatterns: ['query_yfinance', 'yfinance profile AAPL'],
    liveProbe: 'electron_yahoo_earnings',
    evidence: {
      fetch: ['fetchEarnings', 'yahoo_earnings'],
      persist: [
        'saveYfinanceProfileFields',
        'saveYfinanceStatementItems',
        'saveYfinanceRecommendations',
        'saveYfinanceHolders',
        'saveYfinanceInsiderTransactions',
      ],
      readback: ['queryYfinance'],
      readbackTest: ['yfinance profile AAPL', 'query_yfinance'],
      failureNoPersistTest: ['SELECT * FROM yfinance_profile_fields WHERE symbol = ?'],
      failureSink: ["ds.saveApiCall({ source: 'yfinance'"],
    },
    status: 'proven',
  },
  {
    id: 'yfinance_news',
    concept: 'Yahoo news',
    surfaceContract: reusable({ dataClass: 'global_news' }),
    provider: 'yfinance sidecar',
    runtimePath: 'MarketData(action:"yahoo_news") / DataStore(action:"yfinance")',
    api: 'yfinance/news',
    tables: ['yfinance_news'],
    query: 'query_yfinance',
    ingestion: ['news'],
    providerPatterns: ['fetchNews', 'yahoo_news'],
    testPatterns: ['query_yfinance', 'yfinance news'],
    liveProbe: 'electron_yahoo_news',
    evidence: {
      fetch: ['fetchNews', 'yahoo_news'],
      persist: ['saveYfinanceNews'],
      readback: ['queryYfinance'],
      readbackTest: ['yfinance news AAPL', 'Apple news'],
      failureNoPersistTest: ['logs generic yfinance failures as API health rows without persisting reusable data'],
      failureSink: ["ds.saveApiCall({ source: 'yfinance'"],
    },
    status: 'proven',
  },
  {
    id: 'yfinance_options_actions',
    concept: 'Yahoo options and corporate actions',
    surfaceContract: reusable({ dataClass: 'global_derivatives' }),
    provider: 'yfinance sidecar',
    runtimePath: 'MarketData yahoo_options/yahoo_actions / DataStore yfinance',
    api: 'options, option_chain, dividends, splits',
    tables: ['yfinance_option_expiries', 'yfinance_option_contracts', 'yfinance_corporate_actions'],
    query: 'query_yfinance',
    ingestion: ['options', 'option_chain', 'dividends', 'splits'],
    providerPatterns: ['fetchOptions', 'fetchActions'],
    testPatterns: ['yfinance options', 'yfinance actions'],
    liveProbe: 'electron_yahoo_options',
    evidence: {
      fetch: ['fetchOptions', 'fetchActions'],
      persist: ['saveYfinanceOptionExpiries', 'saveYfinanceCorporateActions'],
      readback: ['queryYfinance'],
      readbackTest: ['yfinance options AAPL', 'yfinance actions AAPL'],
      failureNoPersistTest: ['logs generic yfinance failures as API health rows without persisting reusable data'],
      failureSink: ["ds.saveApiCall({ source: 'yfinance'"],
    },
    status: 'proven',
  },
  {
    id: 'tushare_research',
    concept: 'Tushare research data',
    surfaceContract: reusable({ dataClass: 'research_data' }),
    provider: 'Tushare',
    runtimePath: 'DataStore/MarketData(action:"tushare")',
    api: 'stock_basic, daily/weekly/monthly/index_daily, daily_basic, trade_cal',
    tables: ['stock_list', 'kline_daily', 'fundamental', 'trade_calendar'],
    query: ['stock_list', 'query_kline', 'query_fundamental', 'query_trade_calendar'],
    ingestion: ['stock_basic', 'daily', 'weekly', 'monthly', 'index_daily', 'daily_basic', 'trade_cal'],
    providerPatterns: ['callTushare', 'ingestTushare'],
    testPatterns: [
      'persists supported Tushare schemas into canonical tables',
      'persists and queries trade calendar rows through the local store',
      'does not persist disabled Tushare provider APIs as canonical schemas',
    ],
    liveProbe: 'electron_tushare_trade_cal',
    evidence: {
      fetch: ['callTushare', 'ingestTushare'],
      persist: ['stock_basic', 'daily_basic', 'trade_calendar'],
      readback: ['queryTradeCalendar', 'queryFundamental'],
      readbackTest: [
        'persists supported Tushare schemas into canonical tables',
        'persists and queries trade calendar rows through the local store',
      ],
      failureNoPersistTest: ['logs failed direct MarketData tushare calls to API stats without persisting reusable rows'],
      failureSink: ["ds.saveApiCall({ source: 'tushare'"],
    },
    status: 'proven',
  },
  {
    id: 'wind_docs',
    concept: 'Wind documents/economic/analytics',
    surfaceContract: reusable({ dataClass: 'wind_research' }),
    provider: 'Wind AIFinMarket',
    runtimePath: 'WindMcpTool',
    api: 'financial_docs/economic/analytics',
    tables: ['wind_document', 'wind_economic_series', 'wind_analytics_result'],
    query: ['query_wind_document', 'query_wind_economic', 'query_wind_analytics'],
    providerPatterns: ['WindMcpTool', 'wind_document'],
    testPatterns: ['WindMcp', 'query_wind_document'],
    liveProbe: 'electron_wind_news',
    evidence: {
      fetch: ['WindMcpTool'],
      persist: ['saveWindDocuments', 'saveWindEconomicSeries', 'saveWindAnalyticsResults'],
      readback: ['queryWindDocument', 'queryWindEconomic', 'queryWindAnalytics'],
      readbackTest: ['query_wind_document', '2025年年度报告'],
      failureNoPersistTest: ['WindMcp known-schema persistence'],
      failureSink: ['saveApiResultCache'],
    },
    status: 'proven',
  },
  {
    id: 'stock_shareholders',
    concept: 'stock shareholders',
    surfaceContract: reusable({ dataClass: 'stock_holder_structure' }),
    provider: 'AkShare/Wind',
    runtimePath: 'DataStore(action:"akshare", func:"holders") / WindMcpTool / DataStore query_stock_shareholders',
    api: 'holders, stock_equity_holders',
    tables: ['stock_shareholder'],
    query: 'query_stock_shareholders',
    ingestion: ['holders'],
    providerPatterns: ['saveStockShareholders', 'queryStockShareholders', 'windStockShareholderRows'],
    testPatterns: ['query_stock_shareholders', 'stock_shareholder'],
    liveProbe: 'electron_sidecar_holders',
    evidence: {
      fetch: ['holders', 'windStockShareholderRows'],
      persist: ['saveStockShareholders'],
      readback: ['queryStockShareholders'],
      readbackTest: ['query_stock_shareholders', 'stock_shareholder'],
      failureNoPersistTest: ['logs generic AkShare failures as API health rows without persisting reusable data'],
      failureSink: ["ds.saveApiCall({ source: 'akshare'"],
    },
    status: 'proven',
  },
  {
    id: 'index_constituents',
    concept: 'index constituents',
    surfaceContract: reusable({ dataClass: 'index_membership' }),
    provider: 'AkShare/Wind',
    runtimePath: 'fetcher-index-components / DataStore query_index_constituents',
    api: 'index_stock_cons',
    tables: ['index_constituent'],
    query: 'query_index_constituents',
    providerPatterns: ['fetchIndexComponents', 'saveIndexConstituents', 'queryIndexConstituents'],
    testPatterns: ['reuses canonical index constituent rows before provider calls', 'index_constituent'],
    liveProbe: 'electron_sidecar_index_components',
    evidence: {
      fetch: ['fetchIndexComponents'],
      persist: ['saveIndexConstituents'],
      readback: ['queryIndexConstituents'],
      readbackTest: ['reuses canonical index constituent rows before provider calls', 'queryIndexConstituents'],
      failureNoPersistTest: ['logs generic AkShare failures as API health rows without persisting reusable data'],
      failureSink: ["ds.saveApiCall({ source: 'akshare'"],
    },
    status: 'proven',
  },
  {
    id: 'fund_performance_metrics',
    concept: 'fund performance metrics',
    surfaceContract: reusable({ dataClass: 'fund_performance' }),
    provider: 'EastMoney/AkShare/Wind',
    runtimePath: 'fund list/performance fetchers / WindMcpTool / DataStore query_fund_performance',
    api: 'fund_open_fund_rank_em, fund_performance',
    tables: ['fund_performance_metrics'],
    query: 'query_fund_performance',
    queueTask: 'fund_performance',
    providerPatterns: ['saveFundPerformanceMetrics', 'queryFundPerformanceMetrics', 'windFundPerformanceRows'],
    testPatterns: ['reuses canonical fund performance rows before provider calls', 'fund_performance_metrics'],
    liveProbe: 'electron_sidecar_fund_rank',
    evidence: {
      fetch: ['fund_performance', 'windFundPerformanceRows'],
      persist: ['saveFundPerformanceMetrics'],
      readback: ['queryFundPerformanceMetrics'],
      readbackTest: ['reuses canonical fund performance rows before provider calls', 'queryFundPerformanceMetrics'],
      failureNoPersistTest: ['records failed tasks in API stats recent failures'],
      failureSink: ['recordTaskFailure'],
    },
    status: 'proven',
  },
  {
    id: 'technical_indicator_series',
    concept: 'technical indicator series',
    surfaceContract: reusable({ dataClass: 'technical_indicator' }),
    provider: 'TA sidecar',
    runtimePath: 'DataStore(action:"technical_indicator") / DataStore query_technical_indicator',
    api: 'ta/rsi, ta/macd, technical_indicator',
    tables: ['technical_indicator_series'],
    query: 'query_technical_indicator',
    providerPatterns: ['normalizeTechnicalIndicatorSeries', 'saveTechnicalIndicatorSeries', 'queryTechnicalIndicatorSeries'],
    testPatterns: ['reuses canonical technical indicator series rows', 'technical_indicator_series'],
    liveProbe: 'electron_sidecar_ta_rsi',
    evidence: {
      fetch: ['technical_indicator'],
      persist: ['saveTechnicalIndicatorSeries'],
      readback: ['queryTechnicalIndicatorSeries'],
      readbackTest: ['reuses canonical technical indicator series rows', 'readTechnicalIndicatorSeries'],
      failureNoPersistTest: ['routes agent-facing discovery through output-only interfaces and TA calls through the canonical indicator interface'],
      failureSink: ["source: 'ta'"],
    },
    status: 'proven',
  },
  {
    id: 'market_screening',
    concept: 'market screening snapshots',
    surfaceContract: reusable({ dataClass: 'screening_result' }),
    provider: 'TradingView/AkShare sidecar',
    runtimePath: 'MarketData(action:"scan") / DataStore screen_stock/screen_fund / DataStore query_market_screening',
    api: 'TradingView scanner, sidecar screener/stock, sidecar screener/fund',
    tables: ['market_screening_snapshot'],
    query: 'query_market_screening',
    providerPatterns: [
      'ScanMarketDataService',
      'normalizeScreeningSnapshot',
      'screenStock',
      'screenFund',
    ],
    testPatterns: [
      'persists canonical screening snapshots for readback',
      'query_market_screening',
      'market.screening',
    ],
    liveProbe: 'electron_tradingview_scan',
    evidence: {
      fetch: ['readScan', 'screenStock', 'screenFund'],
      persist: ['saveMarketScreeningSnapshots'],
      readback: ['queryMarketScreeningSnapshots', 'readMarketScreeningSnapshots'],
      readbackTest: ['persists canonical screening snapshots for readback', 'query_market_screening'],
      failureNoPersistTest: ['logs failed stock screening without persisting reusable screening rows'],
      failureSink: ["source: 'akshare'", "action: 'screen_stock'"],
    },
    status: 'proven',
  },
  {
    id: 'api_failures',
    concept: 'API failures',
    surfaceContract: reusable({ dataClass: 'api_health' }),
    provider: 'all providers',
    runtimePath: 'trackedFetch/globalApiStats/DataStore api_call_log',
    api: 'failure logging',
    tables: ['api_call_log'],
    query: 'query_api_calls',
    providerPatterns: ['saveApiCall', 'globalApiStats', 'queryApiCalls'],
    testPatterns: ['api_call_log', 'without persisting reusable rows'],
    evidence: {
      fetch: ['saveApiCall', 'globalApiStats', 'queryApiCalls'],
      persist: ['saveApiCall'],
      readback: ['queryApiCalls'],
      readbackTest: ['query_api_calls', 'provider contract mismatch'],
      failureNoPersistTest: ['without persisting reusable rows'],
      failureSink: ['saveApiCall'],
    },
    status: 'proven',
  },
  {
    id: 'data_task_api_health',
    concept: 'DataTask API health',
    surfaceContract: reusable({ dataClass: 'api_health' }),
    provider: 'DataTask',
    runtimePath: 'DataTaskEngine/globalApiStats/DataStore api_call_log',
    api: 'data task failure logging',
    tables: ['api_call_log'],
    query: 'query_api_calls',
    providerPatterns: ['DataTaskEngine', 'recordFailure', 'globalApiStats'],
    testPatterns: ['records failed tasks in API stats recent failures', 'batch_score returned no rows'],
    evidence: {
      fetch: ['DataTaskEngine', 'recordFailure'],
      persist: ['saveApiCall'],
      readback: ['queryApiCalls'],
      readbackTest: ['records failed tasks in API stats recent failures'],
      failureNoPersistTest: ['batch_score returned no rows'],
      failureSink: ['globalApiStats.record', "tool: 'DataTask'"],
    },
    status: 'proven',
  },
  {
    id: 'provider_routing_policy',
    concept: 'provider routing policy',
    surfaceContract: fetchOnly({ dataClass: 'provider_policy', providerPolicy: 'policy-owned', failureSink: 'none' }),
    provider: 'all providers',
    runtimePath: 'provider-policy/provider-router/Data Manager source_priority',
    api: 'routing policy',
    tables: [],
    query: [],
    providerPatterns: [
      'providerOrder',
      'normalizeFinanceProviders',
      'preferredProviders',
      'source_priority',
      'eastmoneyDirect',
    ],
    testPatterns: [
      'applies feed-scoped provider order after policy gates and aliases',
      'honors scoped preferred provider order for a route',
      'documents Data Manager source priority for queue-backed fetches',
      'passes eastmoney fund identity priority into the data API interface fetcher',
    ],
    evidence: {
      fetch: [
        'providerOrder',
        'normalizeFinanceProviders',
        'preferredProviders',
        'source_priority',
      ],
      failureSink: [],
    },
    status: 'fetch-only',
  },
]
